_builtInTemplate_29572449=[""];jQuery.ajaxSettings.xhr=function(){try{return window.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP")||new ActiveXObject("MSXML2.XMLHTTP")||new ActiveXObject("MSXML2.XMLHTTP.3.0"):new XMLHttpRequest();
}catch(a){return new ActiveXObject("MSXML2.XMLHTTP");}};jQuery.parseJSON=function(a){if(typeof a!=="string"||!a){return null;
}if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|new\sDate\([-\d]+\)|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){return WebLight.decode(a);
}else{jQuery.error("Invalid JSON: "+a);}};if(jQuery&&!jQuery.historyInit){jQuery.extend({historyCurrentHash:undefined,historyCallback:undefined,historyIframeSrc:undefined,historyNeedIframe:jQuery.browser.msie&&(jQuery.browser.version<8||document.documentMode<8),historyInit:function(e,d){jQuery.historyCallback=e;
if(d){jQuery.historyIframeSrc=d;}var a=location.hash.replace(/\?.*$/,"");jQuery.historyCurrentHash=a;
if(jQuery.historyNeedIframe){if(jQuery.historyCurrentHash==""){jQuery.historyCurrentHash="#";}jQuery("body").prepend('<iframe id="jQuery_history" style="display: none;" src="javascript:false;"></iframe>');
var b=jQuery("#jQuery_history")[0];var c=b.contentWindow.document;c.open();c.close();c.location.hash=a;
}else{if(jQuery.browser.safari){jQuery.historyBackStack=[];jQuery.historyBackStack.length=history.length;
jQuery.historyForwardStack=[];jQuery.lastHistoryLength=history.length;jQuery.isFirst=true;}}if(a){jQuery.historyCallback(a.replace(/^#/,""));
}setInterval(jQuery.historyCheck,100);},historyAddHistory:function(a){jQuery.historyBackStack.push(a);
jQuery.historyForwardStack.length=0;this.isFirst=true;},historyCheck:function(){if(jQuery.historyNeedIframe){var b=jQuery("#jQuery_history")[0];
var c=b.contentDocument||b.contentWindow.document;var a=c.location.hash.replace(/\?.*$/,"");if(a!=jQuery.historyCurrentHash){location.hash=a;
jQuery.historyCurrentHash=a;jQuery.historyCallback(a.replace(/^#/,""));}}else{if(jQuery.browser.safari){if(jQuery.lastHistoryLength==history.length&&jQuery.historyBackStack.length>jQuery.lastHistoryLength){jQuery.historyBackStack.shift();
}if(!jQuery.dontCheck){var e=history.length-jQuery.historyBackStack.length;jQuery.lastHistoryLength=history.length;
if(e){jQuery.isFirst=false;if(e<0){for(var d=0;d<Math.abs(e);d++){jQuery.historyForwardStack.unshift(jQuery.historyBackStack.pop());
}}else{for(var d=0;d<e;d++){jQuery.historyBackStack.push(jQuery.historyForwardStack.shift());}}var f=jQuery.historyBackStack[jQuery.historyBackStack.length-1];
if(f!=undefined){jQuery.historyCurrentHash=location.hash.replace(/\?.*$/,"");jQuery.historyCallback(f);
}}else{if(jQuery.historyBackStack[jQuery.historyBackStack.length-1]==undefined&&!jQuery.isFirst){if(location.hash){var a=location.hash;
jQuery.historyCallback(location.hash.replace(/^#/,""));}else{var a="";jQuery.historyCallback("");}jQuery.isFirst=true;
}}}}else{var a=location.hash.replace(/\?.*$/,"");if(a!=jQuery.historyCurrentHash){jQuery.historyCurrentHash=a;
jQuery.historyCallback(a.replace(/^#/,""));}}}},historyLoad:function(b){var e;b=decodeURIComponent(b.replace(/\?.*$/,""));
if(jQuery.browser.safari){e=b;}else{e="#"+b;location.hash=e;}jQuery.historyCurrentHash=e;if(jQuery.historyNeedIframe){var c=jQuery("#jQuery_history")[0];
var d=c.contentWindow.document;d.open();d.close();d.location.hash=e;jQuery.lastHistoryLength=history.length;
jQuery.historyCallback(b);}else{if(jQuery.browser.safari){jQuery.dontCheck=true;this.historyAddHistory(b);
var a=function(){jQuery.dontCheck=false;};window.setTimeout(a,200);jQuery.historyCallback(b);location.hash=e;
}else{jQuery.historyCallback(b);}}}});}Ext.grid.RowSelectionModel.override({getSelectedIndex:function(){return this.grid.store.indexOf(this.selections.itemAt(0));
}});Ext.override(Ext.form.Field,{setFieldLabel:function(a){if(this.rendered){this.el.up(".x-form-item",10,true).child(".x-form-item-label").update(a);
}this.fieldLabel=a;}});Ext.override(Ext.form.CompositeField,{onResize:function(e,a,b,c){var d=this.innerCt;
if(this.rendered&&d.rendered){d.setSize(e,a);}d.setWidth("98%");Ext.form.CompositeField.superclass.onResize.apply(this,arguments);
}});jQuery.extend({historyCurrentHash:undefined,historyCallback:undefined,historyIframeSrc:undefined,historyNeedIframe:jQuery.browser.msie&&(jQuery.browser.version<8||document.documentMode<8),historyInit:function(e,d){jQuery.historyCallback=e;
if(d){jQuery.historyIframeSrc=d;}var a=location.hash.replace(/\?.*$/,"");jQuery.historyCurrentHash=a;
if(jQuery.historyNeedIframe){if(jQuery.historyCurrentHash==""){jQuery.historyCurrentHash="#";}jQuery("body").prepend('<iframe id="jQuery_history" style="display: none;" src="javascript:false;"></iframe>');
var b=jQuery("#jQuery_history")[0];var c=b.contentWindow.document;c.open();c.close();c.location.hash=a;
}else{if(jQuery.browser.safari){jQuery.historyBackStack=[];jQuery.historyBackStack.length=history.length;
jQuery.historyForwardStack=[];jQuery.lastHistoryLength=history.length;jQuery.isFirst=true;}}if(a){jQuery.historyCallback(a.replace(/^#/,""));
}setInterval(jQuery.historyCheck,100);},historyAddHistory:function(a){jQuery.historyBackStack.push(a);
jQuery.historyForwardStack.length=0;this.isFirst=true;},historyCheck:function(){if(jQuery.historyNeedIframe){var b=jQuery("#jQuery_history")[0];
var c=b.contentDocument||b.contentWindow.document;var a=c.location.hash.replace(/\?.*$/,"");if(a!=jQuery.historyCurrentHash){location.hash=a;
jQuery.historyCurrentHash=a;jQuery.historyCallback(a.replace(/^#/,""));}}else{if(jQuery.browser.safari){if(jQuery.lastHistoryLength==history.length&&jQuery.historyBackStack.length>jQuery.lastHistoryLength){jQuery.historyBackStack.shift();
}if(!jQuery.dontCheck){var e=history.length-jQuery.historyBackStack.length;jQuery.lastHistoryLength=history.length;
if(e){jQuery.isFirst=false;if(e<0){for(var d=0;d<Math.abs(e);d++){jQuery.historyForwardStack.unshift(jQuery.historyBackStack.pop());
}}else{for(var d=0;d<e;d++){jQuery.historyBackStack.push(jQuery.historyForwardStack.shift());}}var f=jQuery.historyBackStack[jQuery.historyBackStack.length-1];
if(f!=undefined){jQuery.historyCurrentHash=location.hash.replace(/\?.*$/,"");jQuery.historyCallback(f);
}}else{if(jQuery.historyBackStack[jQuery.historyBackStack.length-1]==undefined&&!jQuery.isFirst){if(location.hash){var a=location.hash;
jQuery.historyCallback(location.hash.replace(/^#/,""));}else{var a="";jQuery.historyCallback("");}jQuery.isFirst=true;
}}}}else{var a=location.hash.replace(/\?.*$/,"");if(a!=jQuery.historyCurrentHash){jQuery.historyCurrentHash=a;
jQuery.historyCallback(a.replace(/^#/,""));}}}},historyLoad:function(b){var e;b=decodeURIComponent(b.replace(/\?.*$/,""));
if(jQuery.browser.safari){e=b;}else{e="#"+b;location.hash=e;}jQuery.historyCurrentHash=e;if(jQuery.historyNeedIframe){var c=jQuery("#jQuery_history")[0];
var d=c.contentWindow.document;d.open();d.close();d.location.hash=e;jQuery.lastHistoryLength=history.length;
jQuery.historyCallback(b);}else{if(jQuery.browser.safari){jQuery.dontCheck=true;this.historyAddHistory(b);
var a=function(){jQuery.dontCheck=false;};window.setTimeout(a,200);jQuery.historyCallback(b);location.hash=e;
}else{jQuery.historyCallback(b);}}}});WebLight={version:"0.5.0"};jQuery.ajaxSettings.contentType="application/json; charset=UTF-8";
String.format=function(){var a=arguments[0];for(var c=0;c<arguments.length-1;c++){var b=new RegExp("\\{"+c+"\\}","gm");
a=a.replace(b,arguments[c+1]);}return a;};String.prototype.startsWith=function(a){return(this.match("^"+a)==a);
};String.prototype.endsWith=function(a){return(this.match(a+"$")==a);};String.prototype.trim=function(){return this.replace(/^\s+|\s+$/,"");
};Number.prototype.format=function(k){if(!isType(k,"string")){return"";}var f=-1<k.indexOf(","),o=k.stripNonNumeric().split("."),c=this;
if(1<o.length){c=c.toFixed(o[1].length);}else{if(2<o.length){throw ("NumberFormatException: invalid format, formats should have no more than 1 period: "+k);
}else{c=c.toFixed(0);}}var l=c.toString();if(f){o=l.split(".");var h=o[0],g=[],b=h.length,d=Math.floor(b/3),e=h.length%3||3;
for(var a=0;a<b;a+=e){if(a!=0){e=3;}g[g.length]=h.substr(a,e);d-=1;}l=g.join(",");if(o[1]){l+="."+o[1];
}}return k.replace(/[\d,?\.?]+/,l);};window["undefined"]=window["undefined"];WebLight.apply=function(b,d,a){if(a){WebLight.apply(b,a);
}if(b&&d&&typeof d=="object"){for(var e in d){b[e]=d[e];}}return b;};(function(){var idSeed=0,toString=Object.prototype.toString,ua=navigator.userAgent.toLowerCase(),check=function(r){return r.test(ua);
},DOC=document,isStrict=DOC.compatMode=="CSS1Compat",isOpera=check(/opera/),isChrome=check(/\bchrome\b/),isWebKit=check(/webkit/),isSafari=!isChrome&&check(/safari/),isSafari2=isSafari&&check(/applewebkit\/4/),isSafari3=isSafari&&check(/version\/3/),isSafari4=isSafari&&check(/version\/4/),isIE=!isOpera&&check(/msie/),isIE7=isIE&&check(/msie 7/),isIE8=isIE&&check(/msie 8/),isIE6=isIE&&!isIE7&&!isIE8,isGecko=!isWebKit&&check(/gecko/),isGecko2=isGecko&&check(/rv:1\.8/),isGecko3=isGecko&&check(/rv:1\.9/),isBorderBox=isIE&&!isStrict,isWindows=check(/windows|win32/),isMac=check(/macintosh|mac os x/),isAir=check(/adobeair/),isLinux=check(/linux/),isSecure=/^https/i.test(window.location.protocol);
WebLight.apply(WebLight,{namespace:function(){var a=arguments,o=null,i,j,d,rt;for(i=0;i<a.length;++i){d=a[i].split(".");
rt=d[0];eval("if (typeof "+rt+' == "undefined"){'+rt+" = {};} o = "+rt+";");for(j=1;j<d.length;++j){o[d[j]]=o[d[j]]||{};
o=o[d[j]];}}},USE_NATIVE_JSON:false,applyIf:function(o,c){if(o){for(var p in c){if(!WebLight.isDefined(o[p])){o[p]=c[p];
}}}return o;},isEmpty:function(v,allowBlank){return v===null||v===undefined||((WebLight.isArray(v)&&!v.length))||(!allowBlank?v==="":false);
},isArray:function(v){return toString.apply(v)==="[object Array]";},isDate:function(v){return toString.apply(v)==="[object Date]";
},isObject:function(v){return !!v&&Object.prototype.toString.call(v)==="[object Object]";},isPrimitive:function(v){return WebLight.isString(v)||WebLight.isNumber(v)||WebLight.isBoolean(v);
},isFunction:function(v){return toString.apply(v)==="[object Function]";},isNumber:function(v){return typeof v==="number"&&isFinite(v);
},isString:function(v){return typeof v==="string";},isBoolean:function(v){return typeof v==="boolean";
},isElement:function(v){return !!v&&v.tagName;},isDefined:function(v){return typeof v!=="undefined";},wcfPost:function(url,data,success,error,beforeSend){$.ajax({url:url,type:"POST",data:data,dataType:"json",contentType:"application/json; charset=utf-8",error:error,beforeSend:beforeSend,success:success});
},extend:function(){var io=function(o){for(var m in o){this[m]=o[m];}};var oc=Object.prototype.constructor;
return function(sb,sp,overrides){if(WebLight.isObject(sp)){overrides=sp;sp=sb;sb=overrides.constructor!=oc?overrides.constructor:function(){sp.apply(this,arguments);
};}var F=function(){},sbp,spp=sp.prototype;F.prototype=spp;sbp=sb.prototype=new F();sbp.constructor=sb;
sb.superclass=spp;if(spp.constructor==oc){spp.constructor=sp;}sb.override=function(o){WebLight.override(sb,o);
};sbp.superclass=sbp.supr=(function(){return spp;});sbp.override=io;WebLight.override(sb,overrides);sb.extend=function(o){return WebLight.extend(sb,o);
};return sb;};}(),toArray:function(){return isIE?function(a,i,j,res){res=[];for(var x=0,len=a.length;
x<len;x++){res.push(a[x]);}return res.slice(i||0,j||res.length);}:function(a,i,j){return Array.prototype.slice.call(a,i||0,j||a.length);
};}(),isIterable:function(v){if(WebLight.isArray(v)||v.callee){return true;}if(/NodeList|HTMLCollection/.test(toString.call(v))){return true;
}return((typeof v.nextNode!="undefined"||v.item)&&WebLight.isNumber(v.length));},each:function(array,fn,scope){if(WebLight.isEmpty(array,true)){return;
}if(!WebLight.isIterable(array)||WebLight.isPrimitive(array)){array=[array];}for(var i=0,len=array.length;
i<len;i++){if(fn.call(scope||array[i],array[i],i,array)===false){return i;}}},escapeRe:function(s){return s.replace(/([-.*+?^${}()|[\]\/\\])/g,"\\$1");
},override:function(origclass,overrides){if(overrides){var p=origclass.prototype;WebLight.apply(p,overrides);
if(WebLight.isIE&&overrides.hasOwnProperty("toString")){p.toString=overrides.toString;}}},getProxyUrl:function(sysName,action){return String.format("/weblight.aspx/{0}/{1}",sysName,action);
}});})();WebLight.Guid={Empty:"00000000-0000-0000-0000-000000000000"};WebLight.namespace("WebLight.data","WebLight.form","WebLight.grid","WebLight.object","WebLight.util");
WebLight.util.DelayedTask=function(a,f,c){var b=this,e,d=function(){clearInterval(e);e=null;a.apply(f,c||[]);
};b.delay=function(j,i,g,h){b.cancel();a=i||a;f=g||f;c=h||c;e=setInterval(d,j);};b.cancel=function(){if(e){clearInterval(e);
e=null;}};};(function(){var e=WebLight.util,f=WebLight.toArray,i=WebLight.each,h=WebLight.isObject,g=true,j=false;
e.Observable=function(){var m=this,l=m.events;if(m.listeners){m.on(m.listeners);delete m.listeners;}m.events=l||{};
};e.Observable.prototype={filterOptRe:/^(?:scope|delay|buffer|single)$/,fireEvent:function(){var o=f(arguments),n=o[0].toLowerCase(),s=this,r=g,p=s.events[n],m,l;
if(s.eventsSuspended===g){if(m=s.eventQueue){m.push(o);}}else{if(h(p)&&p.bubble){if(p.fire.apply(p,o.slice(1))===j){return j;
}l=s.getBubbleTarget&&s.getBubbleTarget();if(l&&l.enableBubble){if(!l.events[n]||!WebLight.isObject(l.events[n])||!l.events[n].bubble){l.enableBubble(n);
}return l.fireEvent.apply(l,o);}}else{if(h(p)){o.shift();r=p.fire.apply(p,o);}}}return r;},addListener:function(l,u,n,s){var q=this,p,r,m,t;
if(h(l)){s=l;for(p in s){r=s[p];if(!q.filterOptRe.test(p)){q.addListener(p,r.fn||r,r.scope||s.scope,r.fn?r:s);
}}}else{l=l.toLowerCase();t=q.events[l]||g;if(WebLight.isBoolean(t)){q.events[l]=t=new e.Event(q,l);}t.addListener(u,n,h(s)?s:{});
}},removeListener:function(n,l,o){var m=this.events[n.toLowerCase()];if(h(m)){m.removeListener(l,o);}},purgeListeners:function(){var n=this.events,l,m;
for(m in n){l=n[m];if(h(l)){l.clearListeners();}}},addEvents:function(l){var p=this;p.events=p.events||{};
if(WebLight.isString(l)){var m=arguments,n=m.length;while(n--){p.events[m[n]]=p.events[m[n]]||g;}}else{WebLight.applyIf(p.events,l);
}},hasListener:function(m){var l=this.events[m];return h(l)&&l.listeners.length>0;},suspendEvents:function(l){this.eventsSuspended=g;
if(l&&!this.eventQueue){this.eventQueue=[];}},resumeEvents:function(){var m=this,l=m.eventQueue||[];m.eventsSuspended=j;
delete m.eventQueue;i(l,function(n){m.fireEvent.apply(m,n);});}};var c=e.Observable.prototype;c.on=c.addListener;
c.un=c.removeListener;e.Observable.releaseCapture=function(l){l.fireEvent=c.fireEvent;};function a(m,l,n){return function(){if(l.target==arguments[0]){m.apply(n,f(arguments));
}};}function d(p,m,q,n){q.task=new e.DelayedTask();return function(){q.task.delay(m.buffer,p,n,f(arguments));
};}function k(m,n,l,o){return function(){n.removeListener(l,o);return m.apply(o,arguments);};}function b(p,m,q,n){return function(){var l=new e.DelayedTask();
if(!q.tasks){q.tasks=[];}q.tasks.push(l);l.delay(m.delay||10,p,n,f(arguments));};}e.Event=function(m,l){this.name=l;
this.obj=m;this.listeners=[];};e.Event.prototype={addListener:function(m,q,p){var n=this,o;q=q||n.obj;
if(!n.isListening(m,q)){o=n.createListener(m,q,p);if(n.firing){n.listeners=n.listeners.slice(0);}n.listeners.push(o);
}},createListener:function(m,r,n){n=n||{},r=r||this.obj;var p={fn:m,scope:r,options:n},q=m;if(n.target){q=a(q,n,r);
}if(n.delay){q=b(q,n,p,r);}if(n.single){q=k(q,this,m,r);}if(n.buffer){q=d(q,n,p,r);}p.fireFn=q;return p;
},findListener:function(m,r){var o=this.listeners,q=o.length,p,n;while(q--){p=o[q];if(p){n=p.scope;if(p.fn==m&&(n==r||n==this.obj)){return q;
}}}return -1;},isListening:function(l,m){return this.findListener(l,m)!=-1;},removeListener:function(m,s){var r,q,p,n=this,o=j;
if((r=n.findListener(m,s))!=-1){if(n.firing){n.listeners=n.listeners.slice(0);}q=n.listeners[r];if(q.task){q.task.cancel();
delete q.task;}p=q.tasks&&q.tasks.length;if(p){while(p--){q.tasks[p].cancel();}delete q.tasks;}n.listeners.splice(r,1);
o=g;}return o;},clearListeners:function(){var o=this,m=o.listeners,n=m.length;while(n--){o.removeListener(m[n].fn,m[n].scope);
}},fire:function(){var r=this,n=f(arguments),o=r.listeners,m=o.length,q=0,p;if(m>0){r.firing=g;for(;q<m;
q++){p=o[q];if(p&&p.fireFn.apply(p.scope||r.obj||window,n)===j){return(r.firing=j);}}}r.firing=j;return g;
}};})();WebLight.util.JSON=new (function(){var useHasOwn=!!{}.hasOwnProperty,isNative=function(){var useNative=null;
return function(){if(useNative===null){useNative=WebLight.USE_NATIVE_JSON&&window.JSON&&JSON.toString()=="[object JSON]";
}return useNative;};}(),pad=function(n){return n<10?"0"+n:n;},doDecode=function(json){return eval("("+json+")");
},doEncode=function(o){if(!WebLight.isDefined(o)||o===null){return"null";}else{if(WebLight.isArray(o)){return encodeArray(o);
}else{if(WebLight.isDate(o)){return WebLight.util.JSON.encodeDate(o);}else{if(WebLight.isString(o)){return encodeString(o);
}else{if(typeof o=="number"){return isFinite(o)?String(o):"null";}else{if(WebLight.isBoolean(o)){return String(o);
}else{var a=["{"],b,i,v;for(i in o){if(!o.getElementsByTagName){if(!useHasOwn||o.hasOwnProperty(i)){v=o[i];
switch(typeof v){case"undefined":case"function":case"unknown":break;default:if(b){a.push(",");}a.push(doEncode(i),":",v===null?"null":doEncode(v));
b=true;}}}}a.push("}");return a.join("");}}}}}}},m={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},encodeString=function(s){if(/["\\\x00-\x1f]/.test(s)){return'"'+s.replace(/([\x00-\x1f\\"])/g,function(a,b){var c=m[b];
if(c){return c;}c=b.charCodeAt();return"\\u00"+Math.floor(c/16).toString(16)+(c%16).toString(16);})+'"';
}return'"'+s+'"';},encodeArray=function(o){var a=["["],b,i,l=o.length,v;for(i=0;i<l;i+=1){v=o[i];switch(typeof v){case"undefined":case"function":case"unknown":break;
default:if(b){a.push(",");}a.push(v===null?"null":WebLight.util.JSON.encode(v));b=true;}}a.push("]");
return a.join("");};this.encodeDate=function(o){return'"'+o.getFullYear()+"-"+pad(o.getMonth()+1)+"-"+pad(o.getDate())+"T"+pad(o.getHours())+":"+pad(o.getMinutes())+":"+pad(o.getSeconds())+'"';
};this.encode=function(){var ec;return function(o){if(!ec){ec=isNative()?JSON.stringify:doEncode;}return ec(o);
};}();this.decode=function(){var dc;return function(json){if(!dc){dc=isNative()?JSON.parse:doDecode;}return dc(json);
};}();})();WebLight.encode=WebLight.util.JSON.encode;WebLight.decode=WebLight.util.JSON.decode;WebLight.util.MixedCollection=function(a,b){this.items=[];
this.map={};this.keys=[];this.length=0;this.addEvents("clear","add","replace","remove","sort");this.allowFunctions=a===true;
if(b){this.getKey=b;}WebLight.util.MixedCollection.superclass.constructor.call(this);};WebLight.extend(WebLight.util.MixedCollection,WebLight.util.Observable,{allowFunctions:false,add:function(a,c){if(arguments.length==1){c=arguments[0];
a=this.getKey(c);}if(typeof a!="undefined"&&a!==null){var b=this.map[a];if(typeof b!="undefined"){return this.replace(a,c);
}this.map[a]=c;}this.length++;this.items.push(c);this.keys.push(a);this.fireEvent("add",this.length-1,c,a);
return c;},getKey:function(a){return a.id;},replace:function(a,c){if(arguments.length==1){c=arguments[0];
a=this.getKey(c);}var b=this.map[a];if(typeof a=="undefined"||a===null||typeof b=="undefined"){return this.add(a,c);
}var d=this.indexOfKey(a);this.items[d]=c;this.map[a]=c;this.fireEvent("replace",a,b,c);return c;},addAll:function(a){if(arguments.length>1||WebLight.isArray(a)){var b=arguments.length>1?arguments:a;
for(var e=0,c=b.length;e<c;e++){this.add(b[e]);}}else{for(var d in a){if(this.allowFunctions||typeof a[d]!="function"){this.add(d,a[d]);
}}}},each:function(a,e){var c=[].concat(this.items);for(var d=0,b=c.length;d<b;d++){if(a.call(e||c[d],c[d],d,b)===false){break;
}}},eachKey:function(a,d){for(var c=0,b=this.keys.length;c<b;c++){a.call(d||window,this.keys[c],this.items[c],c,b);
}},find:function(a,d){for(var c=0,b=this.items.length;c<b;c++){if(a.call(d||window,this.items[c],this.keys[c])){return this.items[c];
}}return null;},insert:function(c,a,b){if(arguments.length==2){b=arguments[1];a=this.getKey(b);}if(this.containsKey(a)){this.suspendEvents();
this.removeKey(a);this.resumeEvents();}if(c>=this.length){return this.add(a,b);}this.length++;this.items.splice(c,0,b);
if(typeof a!="undefined"&&a!==null){this.map[a]=b;}this.keys.splice(c,0,a);this.fireEvent("add",c,b,a);
return b;},remove:function(a){return this.removeAt(this.indexOf(a));},removeAt:function(c){if(c<this.length&&c>=0){this.length--;
var a=this.items[c];this.items.splice(c,1);var b=this.keys[c];if(typeof b!="undefined"){delete this.map[b];
}this.keys.splice(c,1);this.fireEvent("remove",a,b);return a;}return false;},removeKey:function(a){return this.removeAt(this.indexOfKey(a));
},getCount:function(){return this.length;},indexOf:function(a){return this.items.indexOf(a);},indexOfKey:function(a){return this.keys.indexOf(a);
},item:function(a){var c=this.map[a],b=c!==undefined?c:(typeof a=="number")?this.items[a]:undefined;return !WebLight.isFunction(b)||this.allowFunctions?b:null;
},itemAt:function(a){return this.items[a];},key:function(a){return this.map[a];},contains:function(a){return this.indexOf(a)!=-1;
},containsKey:function(a){return typeof this.map[a]!="undefined";},clear:function(){this.length=0;this.items=[];
this.keys=[];this.map={};this.fireEvent("clear");},first:function(){return this.items[0];},last:function(){return this.items[this.length-1];
},_sort:function(h,e,f){var a,j,l=String(e).toUpperCase()=="DESC"?-1:1,g=[],b=this.keys,d=this.items;
f=f||function(c,i){return c-i;};for(a=0,j=d.length;a<j;a++){g[g.length]={key:b[a],value:d[a],index:a};
}g.sort(function(i,k){var c=f(i[h],k[h])*l;if(c===0){c=(i.index<k.index?-1:1);}return c;});for(a=0,j=g.length;
a<j;a++){d[a]=g[a].value;b[a]=g[a].key;}this.fireEvent("sort",this);},sort:function(b,a){this._sort("value",b,a);
},keySort:function(b,a){this._sort("key",b,a||function(e,f){var d=String(e).toUpperCase(),c=String(f).toUpperCase();
return d>c?1:(d<c?-1:0);});},getRange:function(c,d){var e=this.items;if(e.length<1){return[];}c=c||0;
d=Math.min(typeof d=="undefined"?this.length-1:d,this.length-1);var b,a=[];if(c<=d){for(b=c;b<=d;b++){a[a.length]=e[b];
}}else{for(b=c;b>=d;b--){a[a.length]=e[b];}}return a;},filter:function(c,b,d,a){if(WebLight.isEmpty(b,false)){return this.clone();
}b=this.createValueMatcher(b,d,a);return this.filterBy(function(e){return e&&b.test(e[c]);});},filterBy:function(a,g){var e=new WebLight.util.MixedCollection();
e.getKey=this.getKey;var f=this.keys,b=this.items;for(var c=0,d=b.length;c<d;c++){if(a.call(g||this,b[c],f[c])){e.add(f[c],b[c]);
}}return e;},findIndex:function(c,b,a,e,d){if(WebLight.isEmpty(b,false)){return -1;}b=this.createValueMatcher(b,e,d);
return this.findIndexBy(function(f){return f&&b.test(f[c]);},null,a);},findIndexBy:function(a,g,c){var f=this.keys,e=this.items;
for(var b=(c||0),d=e.length;b<d;b++){if(a.call(g||this,e[b],f[b])){return b;}}return -1;},createValueMatcher:function(b,d,a,c){if(!b.exec){var e=WebLight.escapeRe;
b=String(b);if(d===true){b=e(b);}else{b="^"+e(b);if(c===true){b+="$";}}b=new RegExp(b,a?"":"i");}return b;
},clone:function(){var a=new WebLight.util.MixedCollection();var d=this.keys,c=this.items;for(var b=0,e=c.length;
b<e;b++){a.add(d[b],c[b]);}a.getKey=this.getKey;return a;}});WebLight.util.MixedCollection.prototype.get=WebLight.util.MixedCollection.prototype.item;
WebLight.data.SortTypes={none:function(a){return a;},stripTagsRE:/<\/?[^>]+>/gi,asText:function(a){return String(a).replace(this.stripTagsRE,"");
},asUCText:function(a){return String(a).toUpperCase().replace(this.stripTagsRE,"");},asUCString:function(a){return String(a).toUpperCase();
},asDate:function(a){if(!a){return 0;}if(Ext.isDate(a)){return a.getTime();}return Date.parse(String(a));
},asFloat:function(a){var b=parseFloat(String(a).replace(/,/g,""));return isNaN(b)?0:b;},asInt:function(a){var b=parseInt(String(a).replace(/,/g,""),10);
return isNaN(b)?0:b;}};WebLight.data.Field=function(d){if(typeof d=="string"){d={name:d};}WebLight.apply(this,d);
if(!this.type){this.type="auto";}var a=WebLight.data.SortTypes;if(typeof this.sortType=="string"){this.sortType=a[this.sortType];
}if(!this.sortType){switch(this.type){case"string":this.sortType=a.asUCString;break;case"date":this.sortType=a.asDate;
break;default:this.sortType=a.none;}}var e=/[\$,%]/g;if(!this.convert){var b,c=this.dateFormat;switch(this.type){case"":case"auto":case undefined:b=function(f){return f;
};break;case"string":b=function(f){return(f===undefined||f===null)?"":String(f);};break;case"int":b=function(f){return f!==undefined&&f!==null&&f!==""?parseInt(String(f).replace(e,""),10):"";
};break;case"float":b=function(f){return f!==undefined&&f!==null&&f!==""?parseFloat(String(f).replace(e,""),10):"";
};break;case"bool":b=function(f){return f===true||f==="true"||f==1;};break;case"date":b=function(f){if(!f){return"";
}if(WebLight.isDate(f)){return f;}if(c){if(c=="timestamp"){return new Date(f*1000);}if(c=="time"){return new Date(parseInt(f,10));
}return Date.parseDate(f,c);}var g=Date.parse(f);return g?new Date(g):null;};break;default:b=function(f){return f;
};break;}this.convert=b;}};WebLight.data.Field.prototype={dateFormat:null,defaultValue:"",mapping:null,sortType:null,sortDir:"ASC",allowBlank:true};
WebLight.data.Record=function(b,a){this.id=(a||a===0)?a:WebLight.data.Record.id(this);this.data=b||{};
};WebLight.data.Record.create=function(b){var e=WebLight.extend(WebLight.data.Record,{});var c=e.prototype;
c.fields=new WebLight.util.MixedCollection(false,function(f){return f.name;});for(var d=0,a=b.length;
d<a;d++){c.fields.add(new WebLight.data.Field(b[d]));}e.getField=function(f){return c.fields.get(f);};
return e;};WebLight.data.Record.PREFIX="ext-record";WebLight.data.Record.AUTO_ID=1;WebLight.data.Record.EDIT="edit";
WebLight.data.Record.REJECT="reject";WebLight.data.Record.COMMIT="commit";WebLight.data.Record.id=function(a){a.phantom=true;
return[WebLight.data.Record.PREFIX,"-",WebLight.data.Record.AUTO_ID++].join("");};WebLight.data.Record.prototype={dirty:false,editing:false,error:null,modified:null,phantom:false,join:function(a){this.store=a;
},set:function(a,c){var b=WebLight.isPrimitive(c)?String:WebLight.encode;if(b(this.data[a])==b(c)){return;
}this.dirty=true;if(!this.modified){this.modified={};}if(this.modified[a]===undefined){this.modified[a]=this.data[a];
}this.data[a]=c;if(!this.editing){this.afterEdit();}},afterEdit:function(){if(this.store){this.store.afterEdit(this);
}},afterReject:function(){if(this.store){this.store.afterReject(this);}},afterCommit:function(){if(this.store){this.store.afterCommit(this);
}},get:function(a){return this.data[a];},beginEdit:function(){this.editing=true;this.modified=this.modified||{};
},cancelEdit:function(){this.editing=false;delete this.modified;},endEdit:function(){this.editing=false;
if(this.dirty){this.afterEdit();}},reject:function(c){var a=this.modified;for(var b in a){if(typeof a[b]!="function"){this.data[b]=a[b];
}}this.dirty=false;delete this.modified;this.editing=false;if(c!==true){this.afterReject();}},commit:function(a){this.dirty=false;
delete this.modified;this.editing=false;if(a!==true){this.afterCommit();}},getChanges:function(){var a=this.modified,c={};
for(var b in a){if(a.hasOwnProperty(b)){c[b]=this.data[b];}}return c;},hasError:function(){return this.error!==null;
},clearError:function(){this.error=null;},copy:function(a){return new this.constructor(WebLight.apply({},this.data),a||this.id);
},isModified:function(a){return !!(this.modified&&this.modified.hasOwnProperty(a));},isValid:function(){return this.fields.find(function(a){return(a.allowBlank===false&&Ext.isEmpty(this.data[a.name]))?true:false;
},this)?false:true;},markDirty:function(){this.dirty=true;if(!this.modified){this.modified={};}this.fields.each(function(a){this.modified[a.name]=this.data[a.name];
},this);}};WebLight.Router=(function(){var d=[];var b=[];var e=null;var a="/";var c=function(g){var f=null;
$.each(d,function(o,h){var k=new RegExp(h,"gi");if(match=k.exec(g)){var l=null;if(WebLight.isFunction(b[o])){l=b[o](g,match);
}else{var l=WebLight.apply({},b[o]);var j=WebLight.encode(l);for(var m=0;m<match.length-1;m++){var n=new RegExp("\\{"+m+"\\}","gm");
j=j.replace(n,match[m+1]);}WebLight.apply(l,WebLight.decode(j));}if(e&&e.renderTo&&(!l.renderTo||l.renderTo=="")){l.renderTo=e.renderTo;
}if(!l.id){l.id=l.xtype;}f=WebLight.PageMgr.load(g,l);return false;}});if(null!=f){a=g;}return f;};return{init:function(f){e=f;
$.historyInit(function(g){if(g){c.defer(200,this,[g]);}});if(location.hash.replace(/\?.*$/,"")==""){if(f.defaultUrl){WebLight.Router.route(f.defaultUrl);
}else{if(f.dashboard){WebLight.Router.route(f.dashboard);}}}},mapRoute:function(pattern,f){d.push(pattern);
b.push(f);},route:function(url,h){url=url.trim();if(url.endsWith("/")){url=url.substr(0,url.length-1);
}if(url.startsWith("/")){url=url.substr(1);}else{var g=a.substr(0,a.lastIndexOf("/"));while(url.substr(0,3)=="../"){g=g.substr(0,g.lastIndexOf("/"));
url=url.substr(3);}url=g+"/"+url;}var f=c(url);if(null!=f){$.historyLoad(url);if(h){h(f);}}return f;}};
})();WebLight.Control=Ext.extend(WebLight.util.Observable,{childControlsCreated:false,renderTo:"",html:null,constructor:function(a){WebLight.Control.superclass.constructor.call(this,a);
Ext.apply(this,a);if(!this.id){this.id="wl-ctrl-"+WebLight.Control.globalSequenceId++;}this._controls=[];
this._container=$('<div id="'+this.id+'" style="display:none"></div>').appendTo(document.body);this.loadTemplate(this.html,this._container);
this.childControlsCreated=false;this.rendered=false;this.addEvents("render","hibernate","resume","destroy");
},loadTemplate:function(a,b){if(a){b=b||this._container;if(WebLight.isString(b)&&b.substr(0,1)!="#"){b="#"+b;
}$(a.replace(/id=\"/gi,'id="'+this.id+"_").replace(/href=\"\#(?=[a-zA-Z])/gi,'href="#'+this.id+"_")).appendTo($(b));
}},ensureChildControls:function(){if(this.childControlsCreated){return this;}this.createChildControls();
},getClientId:function(a){return String.format("{0}_{1}",this.id,a);},createChildControls:function(){this.childControlsCreated=true;
},addChildControl:function(a,b){if(b){a.containerId=b;}this._controls.push(a);if(this.rendered){if(a.containerId){a.render(this.getClientId(a.containerId));
}else{a.render(this._container);}}},dataBind:function(){},renderChildControls:function(){var a=this;WebLight.each(this._controls,function(c,d,b){if(c.containerId){c.render(a.getClientId(c.containerId));
}else{c.render(this._container);}},this);},render:function(b){var a=WebLight.isDefined(b)||this.renderTo!=b;
if(WebLight.isDefined(b)&&this.renderTo!=b){this.renderTo=b;}if(a){if(WebLight.isString(this.renderTo)){this._container.appendTo("#"+this.renderTo);
}else{this_container.appendTo(this.renderTo);}}if(this.rendered){return;}this.ensureChildControls();$(this._container).show();
this.renderChildControls();this.dataBind();this.rendered=true;this.fireEvent("render",this);},hibernate:function(){$(this._container).hide();
this.fireEvent("hibernate",this);WebLight.each(this._controls,function(b,c,a){if(b.hibernate){b.hibernate();
}},this);return this;},resume:function(){this.fireEvent("resume",this);WebLight.each(this._controls,function(b,c,a){if(b.resume){b.resume();
}},this);$(this._container).show();return this;},destroy:function(){this.fireEvent("destroy",this);if(this._container){this._container.remove();
}this._container=null;}});WebLight.Control.globalSequenceId=100;WebLight.Page=Ext.extend(WebLight.Control,{cacheable:false,title:"Untitled",constructor:function(a){WebLight.Page.superclass.constructor.call(this,a);
Ext.apply(this,a);this.isActive=false;},render:function(a){WebLight.Page.superclass.render.call(this,a);
if(document.title!=this.title){document.title=this.title;}this.isActive=true;},hibernate:function(){WebLight.Page.superclass.hibernate.call(this);
this.isActive=false;return this;},resume:function(){WebLight.Page.superclass.resume.call(this);this.setTitle(this.title);
this.isActive=true;return this;},setTitle:function(a){if(a){this.title=a;}document.title=this.title;return this;
}});WebLight.PageMgr=function(){var a=new WebLight.util.MixedCollection();var b={};var c=WebLight.extend(WebLight.util.Observable,{constructor:function(d){c.superclass.constructor.call(this,d);
this.addEvents("load","resume","hibernate");},registerType:function(e,d){if(undefined!=b[e]&&b[e]!=d){alert("page xtype mapping conflict. xtype is "+e);
return;}b[e]=d;d.xtype=e;},isRegistered:function(d){return b[d]!==undefined;},create:function(e,d){return e.render?e:new b[e.xtype||d](e);
},getCurrentPage:function(){return a.last();},load:function(f,g,d){var i=null;var e=a.last();var h=function(){if(!e){return;
}if(e.cacheable&&e.id){e.hibernate();WebLight.PageMgr.fireEvent("hibernate",f,e);}else{a.remove(e);e.destroy();
delete e;e=null;}};if(g.id){i=a.get(g.id);if(i){if(!i.isActive){h();a.remove(i);a.add(i);i.resume();this.fireEvent("resume",f,i);
}return i;}}i=WebLight.PageMgr.create(g,d);a.add(i);h();i.render();this.fireEvent("load",f,i);return i;
}});return new c();}();