jQuery.ajaxSettings.xhr=function(){try{return window.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP")||new ActiveXObject("MSXML2.XMLHTTP")||new ActiveXObject("MSXML2.XMLHTTP.3.0"):new XMLHttpRequest();
}catch(a){return new ActiveXObject("MSXML2.XMLHTTP");}};jQuery.parseJSON=function(a){if(typeof a!=="string"||!a){return null;
}if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|new\sDate\([-\d]+\)|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){return WebLight.decode(a);
}else{jQuery.error("Invalid JSON: "+a);}};if(jQuery&&!jQuery.historyInit){jQuery.extend({historyCurrentHash:undefined,historyCallback:undefined,historyIframeSrc:undefined,historyNeedIframe:jQuery.browser.msie&&(jQuery.browser.version<8||document.documentMode<8),historyInit:function(d,b){jQuery.historyCallback=d;
if(b){jQuery.historyIframeSrc=b;}var a=location.hash.replace(/\?.*$/,"");jQuery.historyCurrentHash=a;
if(jQuery.historyNeedIframe){if(jQuery.historyCurrentHash==""){jQuery.historyCurrentHash="#";}jQuery("body").prepend('<iframe id="jQuery_history" style="display: none;" src="javascript:false;"></iframe>');
var e=jQuery("#jQuery_history")[0];var c=e.contentWindow.document;c.open();c.close();c.location.hash=a;
}else{if(jQuery.browser.safari){jQuery.historyBackStack=[];jQuery.historyBackStack.length=history.length;
jQuery.historyForwardStack=[];jQuery.lastHistoryLength=history.length;jQuery.isFirst=true;}}if(a){jQuery.historyCallback(a.replace(/^#/,""));
}setInterval(jQuery.historyCheck,100);},historyAddHistory:function(a){jQuery.historyBackStack.push(a);
jQuery.historyForwardStack.length=0;this.isFirst=true;},historyCheck:function(){if(jQuery.historyNeedIframe){var f=jQuery("#jQuery_history")[0];
var e=f.contentDocument||f.contentWindow.document;var b=e.location.hash.replace(/\?.*$/,"");if(b!=jQuery.historyCurrentHash){location.hash=b;
jQuery.historyCurrentHash=b;jQuery.historyCallback(b.replace(/^#/,""));}}else{if(jQuery.browser.safari){if(jQuery.lastHistoryLength==history.length&&jQuery.historyBackStack.length>jQuery.lastHistoryLength){jQuery.historyBackStack.shift();
}if(!jQuery.dontCheck){var c=history.length-jQuery.historyBackStack.length;jQuery.lastHistoryLength=history.length;
if(c){jQuery.isFirst=false;if(c<0){for(var a=0;a<Math.abs(c);a++){jQuery.historyForwardStack.unshift(jQuery.historyBackStack.pop());
}}else{for(var a=0;a<c;a++){jQuery.historyBackStack.push(jQuery.historyForwardStack.shift());}}var d=jQuery.historyBackStack[jQuery.historyBackStack.length-1];
if(d!=undefined){jQuery.historyCurrentHash=location.hash.replace(/\?.*$/,"");jQuery.historyCallback(d);
}}else{if(jQuery.historyBackStack[jQuery.historyBackStack.length-1]==undefined&&!jQuery.isFirst){if(location.hash){var b=location.hash;
jQuery.historyCallback(location.hash.replace(/^#/,""));}else{var b="";jQuery.historyCallback("");}jQuery.isFirst=true;
}}}}else{var b=location.hash.replace(/\?.*$/,"");if(b!=jQuery.historyCurrentHash){jQuery.historyCurrentHash=b;
jQuery.historyCallback(b.replace(/^#/,""));}}}},historyLoad:function(e){var a;e=decodeURIComponent(e.replace(/\?.*$/,""));
if(jQuery.browser.safari){a=e;}else{a="#"+e;location.hash=a;}jQuery.historyCurrentHash=a;if(jQuery.historyNeedIframe){var b=jQuery("#jQuery_history")[0];
var d=b.contentWindow.document;d.open();d.close();d.location.hash=a;jQuery.lastHistoryLength=history.length;
jQuery.historyCallback(e);}else{if(jQuery.browser.safari){jQuery.dontCheck=true;this.historyAddHistory(e);
var c=function(){jQuery.dontCheck=false;};window.setTimeout(c,200);jQuery.historyCallback(e);location.hash=a;
}else{jQuery.historyCallback(e);}}}});}Ext.grid.RowSelectionModel.override({getSelectedIndex:function(){return this.grid.store.indexOf(this.selections.itemAt(0));
}});Ext.override(Ext.form.Field,{setFieldLabel:function(a){if(this.rendered){this.el.up(".x-form-item",10,true).child(".x-form-item-label").update(a);
}this.fieldLabel=a;}});Ext.override(Ext.form.CompositeField,{onResize:function(c,e,b,a){var d=this.innerCt;
if(d){if(this.rendered&&d.rendered){d.setSize(c,e);}d.setWidth("98%");}Ext.form.CompositeField.superclass.onResize.apply(this,arguments);
}});jQuery.extend({historyCurrentHash:undefined,historyCallback:undefined,historyIframeSrc:undefined,historyNeedIframe:jQuery.browser.msie&&(jQuery.browser.version<8||document.documentMode<8),historyInit:function(d,b){jQuery.historyCallback=d;
if(b){jQuery.historyIframeSrc=b;}var a=location.hash.replace(/\?.*$/,"");jQuery.historyCurrentHash=a;
if(jQuery.historyNeedIframe){if(jQuery.historyCurrentHash==""){jQuery.historyCurrentHash="#";}jQuery("body").prepend('<iframe id="jQuery_history" style="display: none;" src="javascript:false;"></iframe>');
var e=jQuery("#jQuery_history")[0];var c=e.contentWindow.document;c.open();c.close();c.location.hash=a;
}else{if(jQuery.browser.safari){jQuery.historyBackStack=[];jQuery.historyBackStack.length=history.length;
jQuery.historyForwardStack=[];jQuery.lastHistoryLength=history.length;jQuery.isFirst=true;}}if(a){jQuery.historyCallback(a.replace(/^#/,""));
}setInterval(jQuery.historyCheck,100);},historyAddHistory:function(a){jQuery.historyBackStack.push(a);
jQuery.historyForwardStack.length=0;this.isFirst=true;},historyCheck:function(){if(jQuery.historyNeedIframe){var f=jQuery("#jQuery_history")[0];
var e=f.contentDocument||f.contentWindow.document;var b=e.location.hash.replace(/\?.*$/,"");if(b!=jQuery.historyCurrentHash){location.hash=b;
jQuery.historyCurrentHash=b;jQuery.historyCallback(b.replace(/^#/,""));}}else{if(jQuery.browser.safari){if(jQuery.lastHistoryLength==history.length&&jQuery.historyBackStack.length>jQuery.lastHistoryLength){jQuery.historyBackStack.shift();
}if(!jQuery.dontCheck){var c=history.length-jQuery.historyBackStack.length;jQuery.lastHistoryLength=history.length;
if(c){jQuery.isFirst=false;if(c<0){for(var a=0;a<Math.abs(c);a++){jQuery.historyForwardStack.unshift(jQuery.historyBackStack.pop());
}}else{for(var a=0;a<c;a++){jQuery.historyBackStack.push(jQuery.historyForwardStack.shift());}}var d=jQuery.historyBackStack[jQuery.historyBackStack.length-1];
if(d!=undefined){jQuery.historyCurrentHash=location.hash.replace(/\?.*$/,"");jQuery.historyCallback(d);
}}else{if(jQuery.historyBackStack[jQuery.historyBackStack.length-1]==undefined&&!jQuery.isFirst){if(location.hash){var b=location.hash;
jQuery.historyCallback(location.hash.replace(/^#/,""));}else{var b="";jQuery.historyCallback("");}jQuery.isFirst=true;
}}}}else{var b=location.hash.replace(/\?.*$/,"");if(b!=jQuery.historyCurrentHash){jQuery.historyCurrentHash=b;
jQuery.historyCallback(b.replace(/^#/,""));}}}},historyLoad:function(e){var a;e=decodeURIComponent(e.replace(/\?.*$/,""));
if(jQuery.browser.safari){a=e;}else{a="#"+e;location.hash=a;}jQuery.historyCurrentHash=a;if(jQuery.historyNeedIframe){var b=jQuery("#jQuery_history")[0];
var d=b.contentWindow.document;d.open();d.close();d.location.hash=a;jQuery.lastHistoryLength=history.length;
jQuery.historyCallback(e);}else{if(jQuery.browser.safari){jQuery.dontCheck=true;this.historyAddHistory(e);
var c=function(){jQuery.dontCheck=false;};window.setTimeout(c,200);jQuery.historyCallback(e);location.hash=a;
}else{jQuery.historyCallback(e);}}}});jQuery.cookie=function(k,a,c){if(typeof a!="undefined"){c=c||{};
if(a===null){a="";c=$.extend({},c);c.expires=-1;}var b="";if(c.expires&&(typeof c.expires=="number"||c.expires.toUTCString)){var f;
if(typeof c.expires=="number"){f=new Date();f.setTime(f.getTime()+(c.expires*24*60*60*1000));}else{f=c.expires;
}b="; expires="+f.toUTCString();}var g=c.path?"; path="+(c.path):"";var j=c.domain?"; domain="+(c.domain):"";
var m=c.secure?"; secure":"";document.cookie=[k,"=",encodeURIComponent(a),b,g,j,m].join("");}else{var l=null;
if(document.cookie&&document.cookie!=""){var h=document.cookie.split(";");for(var d=0;d<h.length;d++){var e=jQuery.trim(h[d]);
if(e.substring(0,k.length+1)==(k+"=")){l=decodeURIComponent(e.substring(k.length+1));break;}}}return l;
}};WebLight={version:"1.10.0909"};jQuery.ajaxSettings.contentType="application/json; charset=UTF-8";String.format=function(){var b=arguments[0];
for(var a=0;a<arguments.length-1;a++){var c=new RegExp("\\{"+a+"\\}","gm");b=b.replace(c,arguments[a+1]);
}return b;};String.prototype.startsWith=function(a){return(this.match("^"+a)==a);};String.prototype.endsWith=function(a){return(this.match(a+"$")==a);
};String.prototype.trim=function(){return this.replace(/^\s+|\s+$/,"");};Array.prototype.indexOf=function(f,d,c){for(var a=+d||0,e=this.length;
a<e;a++){if(this[a]===f||c&&this[a]==f){return a;}}return -1;};Array.prototype.unique=function(e){var d=[],c,f=this.length;
for(c=0;c<f;c++){if(d.indexOf(this[c],0,e)<0){d.push(this[c]);}}return d;};Number.prototype.format=function(a){if(!isType(a,"string")){return"";
}var o=-1<a.indexOf(","),k=a.stripNonNumeric().split("."),l=this;if(1<k.length){l=l.toFixed(k[1].length);
}else{if(2<k.length){throw ("NumberFormatException: invalid format, formats should have no more than 1 period: "+a);
}else{l=l.toFixed(0);}}var h=l.toString();if(o){k=h.split(".");var e=k[0],c=[],d=e.length,f=Math.floor(d/3),g=e.length%3||3;
for(var b=0;b<d;b+=g){if(b!=0){g=3;}c[c.length]=e.substr(b,g);f-=1;}h=c.join(",");if(k[1]){h+="."+k[1];
}}return a.replace(/[\d,?\.?]+/,h);};window["undefined"]=window["undefined"];WebLight.apply=function(a,d,b){if(b){WebLight.apply(a,b);
}if(a&&d&&typeof d=="object"){for(var e in d){a[e]=d[e];}}return a;};(function(){var idSeed=0,toString=Object.prototype.toString,ua=navigator.userAgent.toLowerCase(),check=function(r){return r.test(ua);
},DOC=document,isStrict=DOC.compatMode=="CSS1Compat",isOpera=check(/opera/),isChrome=check(/\bchrome\b/),isWebKit=check(/webkit/),isSafari=!isChrome&&check(/safari/),isSafari2=isSafari&&check(/applewebkit\/4/),isSafari3=isSafari&&check(/version\/3/),isSafari4=isSafari&&check(/version\/4/),isIE=!isOpera&&check(/msie/),isIE7=isIE&&check(/msie 7/),isIE8=isIE&&check(/msie 8/),isIE6=isIE&&!isIE7&&!isIE8,isGecko=!isWebKit&&check(/gecko/),isGecko2=isGecko&&check(/rv:1\.8/),isGecko3=isGecko&&check(/rv:1\.9/),isBorderBox=isIE&&!isStrict,isWindows=check(/windows|win32/),isMac=check(/macintosh|mac os x/),isAir=check(/adobeair/),isLinux=check(/linux/),isSecure=/^https/i.test(window.location.protocol);
WebLight.apply(WebLight,{namespace:function(){var a=arguments,o=null,i,j,d,rt;for(i=0;i<a.length;++i){d=a[i].split(".");
rt=d[0];eval("if (typeof "+rt+' == "undefined"){'+rt+" = {};} o = "+rt+";");for(j=1;j<d.length;++j){o[d[j]]=o[d[j]]||{};
o=o[d[j]];}}},USE_NATIVE_JSON:false,applyIf:function(o,c){if(o){for(var p in c){if(!WebLight.isDefined(o[p])){o[p]=c[p];
}}}return o;},isEmpty:function(v,allowBlank){return v===null||v===undefined||((WebLight.isArray(v)&&!v.length))||(!allowBlank?v==="":false);
},isArray:function(v){return toString.apply(v)==="[object Array]";},isDate:function(v){return toString.apply(v)==="[object Date]";
},isObject:function(v){return !!v&&Object.prototype.toString.call(v)==="[object Object]";},isPrimitive:function(v){return WebLight.isString(v)||WebLight.isNumber(v)||WebLight.isBoolean(v);
},isFunction:function(v){return toString.apply(v)==="[object Function]";},isNumber:function(v){return typeof v==="number"&&isFinite(v);
},isString:function(v){return typeof v==="string";},isBoolean:function(v){return typeof v==="boolean";
},isElement:function(v){return !!v&&v.tagName;},isDefined:function(v){return typeof v!=="undefined";},wcfPost:function(url,data,success,error,beforeSend){return $.ajax({url:url,type:"POST",data:data,dataType:"json",contentType:"application/json; charset=utf-8",error:error,beforeSend:beforeSend,success:success});
},post:function(url,data,success,error){if(jQuery.isFunction(data)){error=error||success;success=data;
data={};}return jQuery.ajax({type:"POST",url:url,data:data,success:success,error:error,dataType:"json",contentType:"application/json; charset=utf-8"});
},extend:function(){var io=function(o){for(var m in o){this[m]=o[m];}};var oc=Object.prototype.constructor;
return function(sb,sp,overrides){if(WebLight.isObject(sp)){overrides=sp;sp=sb;sb=overrides.constructor!=oc?overrides.constructor:function(){sp.apply(this,arguments);
};}var F=function(){},sbp,spp=sp.prototype;F.prototype=spp;sbp=sb.prototype=new F();sbp.constructor=sb;
sb.superclass=spp;if(spp.constructor==oc){spp.constructor=sp;}sb.override=function(o){WebLight.override(sb,o);
};sbp.superclass=sbp.supr=(function(){return spp;});sbp.override=io;WebLight.override(sb,overrides);sb.extend=function(o){return WebLight.extend(sb,o);
};return sb;};}(),toArray:function(){return isIE?function(a,i,j,res){res=[];for(var x=0,len=a.length;
x<len;x++){res.push(a[x]);}return res.slice(i||0,j||res.length);}:function(a,i,j){return Array.prototype.slice.call(a,i||0,j||a.length);
};}(),isIterable:function(v){if(WebLight.isArray(v)||v.callee){return true;}if(/NodeList|HTMLCollection/.test(toString.call(v))){return true;
}return((typeof v.nextNode!="undefined"||v.item)&&WebLight.isNumber(v.length));},each:function(array,fn,scope){if(WebLight.isEmpty(array,true)){return;
}if(!WebLight.isIterable(array)||WebLight.isPrimitive(array)){array=[array];}for(var i=0,len=array.length;
i<len;i++){if(fn.call(scope||array[i],array[i],i,array)===false){return i;}}},escapeRe:function(s){return s.replace(/([-.*+?^${}()|[\]\/\\])/g,"\\$1");
},override:function(origclass,overrides){if(overrides){var p=origclass.prototype;WebLight.apply(p,overrides);
if(WebLight.isIE&&overrides.hasOwnProperty("toString")){p.toString=overrides.toString;}}},getProxyUrl:function(sysName,action){return String.format("/weblight.aspx/{0}/{1}",sysName,action);
},getMethodUrl:function(sysName,action){return String.format("/weblight.aspx/{0}/{1}",sysName,action);
},newGuid:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c=="x"?r:(r&3|8);
return v.toString(16);}).toUpperCase();},clone:function(o){if(!o||"object"!==typeof o){return o;}if("function"===typeof o.clone){return o.clone();
}var c="[object Array]"===Object.prototype.toString.call(o)?[]:{};var p,v;for(p in o){if(o.hasOwnProperty(p)){v=o[p];
if(v&&"object"===typeof v){c[p]=WebLight.clone(v);}else{c[p]=v;}}}return c;},urlEncodeCharacter:function(c){return"%"+c.charCodeAt(0).toString(16);
},urlDecodeCharacter:function(str,c){return String.fromCharCode(parseInt(c,16));},urlEncode:function(s){return encodeURIComponent(s).replace(/\%20/g,"+").replace(/[!'()*~]/g,WebLight.urlEncodeCharacter);
},urlDecode:function(s){return decodeURIComponent(s.replace(/\+/g,"%20")).replace(/\%([0-9a-f]{2})/g,WebLight.urlDecodeCharacter);
}});})();WebLight.override(RegExp,{escape:function(a){if("string"!==typeof a){return a;}return a.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1");
},clone:function(){return new RegExp(this);}});WebLight.override(Array,{copy:function(){var c=[];for(var b=0,d=this.length;
b<d;b++){c.push(this[b]);}return c;},indexOf:function(e,c){for(var a=+c||0,d=this.length;a<d;a++){if(this[a]===e){return a;
}}return -1;},intersect:function(){if(!arguments.length){return[];}var g=this,f,e;for(var c=0,h=arguments.length;
c<h;c++){e=[];f=arguments[c]||[];for(var b=0,d=g.length;b<d;b++){if(-1<f.indexOf(g[b])){e.push(g[b]);
}}g=e;}return e.unique();},lastIndexOf:function(d,c){c=+c||0;var a=this.length;while(a-->c){if(this[a]===d){return a;
}}return -1;},union:function(){var e=this.copy(),f;for(var c=0,g=arguments.length;c<g;c++){f=arguments[c]||[];
for(var b=0,d=f.length;b<d;b++){e.push(f[b]);}}return e.unique();},unique:function(){var c=[],b,d=this.length;
for(b=0;b<d;b++){if(c.indexOf(this[b])<0){c.push(this[b]);}}return c;}});if(!Array.prototype.map){Array.prototype.map=function(b){var c=this.length;
if(typeof b!="function"){throw new TypeError();}var a=new Array(c);var d=arguments[1];for(var e=0;e<c;
e++){if(e in this){a[e]=b.call(d,this[e],e,this);}}return a;};}WebLight.namespace("WebLight.data","WebLight.form","WebLight.grid","WebLight.object","WebLight.util");
WebLight.util.MixedCollection=Ext.util.MixedCollection;WebLight.util.Json=Ext.util.JSON;WebLight.util.Observable=Ext.util.Observable;
WebLight.util.DelayedTask=Ext.util.DelayedTask;WebLight.data.SortTypes=Ext.data.SortTypes;WebLight.data.Field=Ext.data.Field;
WebLight.data.Record=Ext.data.Record;WebLight.encode=Ext.util.JSON.encode;WebLight.decode=Ext.util.JSON.decode;
WebLight.data.Queryable=WebLight.extend(WebLight.util.Observable,{store:null,constructor:function(a){WebLight.apply(this,a);
WebLight.data.Queryable.superclass.constructor.call(this,a);this.params={};},skip:function(a){if(this.store&&WebLight.isDefined(this.store.setBaseParam)){this.store.setBaseParam(this.store.paramNames.start,a);
}this.params.start=a;return this;},take:function(a){if(this.store&&WebLight.isDefined(this.store.setBaseParam)){this.store.setBaseParam(this.store.paramNames.limit,a);
}this.params.limit=a;return this;},orderBy:function(b){var a=b.split(" ");this.params.sort=a[0];this.params.dir=a.length==1?"ASC":a[1];
if(this.store&&WebLight.isDefined(this.store.setBaseParam)){this.store.setBaseParam(this.store.paramNames.sort,a[0]);
this.store.setBaseParam(this.store.paramNames.dir,a.length==1?"ASC":a[1]);}return this;},where:function(j,d){if(arguments.length==0||!j||j.trim()==""){this.lastPredicate="";
this.params.filters=[];if(this.store&&WebLight.isDefined(this.store.setBaseParam)){this.store.setBaseParam("filters",[]);
}return this;}if(arguments.length>1){var k=arguments[0];for(var b=0;b<arguments.length-1;b++){var h=new RegExp("\\@"+b,"gm");
var a=arguments[b+1];if(WebLight.isArray(a)){a=a.join(",");}else{if(WebLight.isDate(a)){a=WebLight.encode(a);
}}k=k.replace(h,a);}j=k;}if(j.startsWith("&&")&&this.lastPredicate){j=this.lastPredicate+" "+j;}var g=[];
var h=/(^|\s+\&\&\s+)([\w-]+)\s*([\[\]\^\!\<\>\=\%]{1,2})\s*\"?([\w\,\s\:\-]*\w)\"?/g;while(match=h.exec(j)){var l=match[2];
var c=match[3];var a=match[4];var f=this.recordType.getField(l);if(f){var e={field:l,data:{value:a,type:c=="[]"?"list":f.type.type}};
switch(c){case"==":e.data.comparison="eq";break;case">":e.data.comparison="gt";break;case"<":e.data.comparison="lt";
break;case">=":e.data.comparison="nl";break;case"<=":e.data.comparison="ng";break;case"!=":e.data.comparison="nq";
break;case"^!":e.data.comparison="ns";break;case"%%":e.data.comparison="ct";break;case"^=":e.data.comparison="sw";
break;}g.push(e);}}this.lastPredicate=j;this.store.setBaseParam("filters",g);this.params.filters=g;return this;
},property:function(d,a){if(!this._properties){this._properties={};}if(d===null){this._properties={};
this.store.setBaseParam("_properties",Ext.encode(this._properties));return this;}if(arguments.length==1&&WebLight.isString(arguments[0])){return this._properties[d];
}var b;if(!WebLight.isObject(d)){b={};b[d]=a;}else{b=d;}WebLight.apply(this._properties,b);for(var c in this._properties){if(this._properties[c]===undefined||this._properties[c]===null||this._properties[c]===""){delete this._properties[c];
}}this.store.setBaseParam("_properties",Ext.encode(this._properties));return this;},load:function(){if(this.store&&WebLight.isDefined(this.store.load)){this.store.load();
}return this;}});WebLight.data.Store=Ext.extend(Ext.data.Store,{trackingChanges:false,discardMessage:"Your changes have not been saved. \r\n\r\n Discard the changes?",constructor:function(b){b=b||{};
var f=this;var a=this;WebLight.data.Store.superclass.constructor.call(this,b);this.changes=[];this.boundControls=[];
var h=function(i){if(null==f._computedFields){return;}WebLight.each(f._computedFields,function(l,k){var j=0;
switch(l[1]){case"func":j=l[2](i);break;case"sum":var j=0;WebLight.each(l[2],function(n,m){j+=i.get(n)||0;
});break;}if(i.get(l[0]!=j)){i.set(l[0],j);}});};var d=function(i){if(f._columnSummaryRelations==null){return;
}WebLight.each(f._columnSummaryRelations,function(k,l){var j=0;WebLight.each(k[1],function(m,n){var o=i.get(m);
if(o){j+=o;}});if(i.get(k[0])!=j){i.set(k[0],j);}});};var e=function(i){if(null==f._rowSummaryRelations){return;
}WebLight.each(f._rowSummaryRelations,function(j,k){if(!i||j[2].indexOf(i)!=-1){WebLight.each(j[1],function(m){var l=0;
WebLight.each(j[2],function(n){var o=n.get(m);if(o){l+=o;}});if(j[0].get(m)!=l){j[0].set(m,l);}});}});
};this.on("add",function(k,j,i){Ext.each(j,function(l){if(k.changes.indexOf(l)==-1){k.changes.push(l);
h(l);d(l);e(l);}},this);});this.on("remove",function(l,i,k){var j=i.get("_sysStatus");if(j==1){l.changes.remove(i);
}else{if(l.changes.indexOf(i)<0){l.changes.push(i);}}i.set("_sysStatus",3);});this.on("update",function(k,i,j){if(j==Ext.data.Record.REJECT||j==Ext.data.Record.COMMIT){if(k.changes.indexOf(i)>=0){k.changes.remove(i);
}if(j==Ext.data.Record.REJECT&&i.get("_sysStatus")==1){this.remove(i);}}else{if(j==Ext.data.Record.EDIT){if(k.changes.indexOf(i)==-1){k.changes.push(i);
if(i.get("_sysStatus")!=1){i.set("_sysStatus",2);}}h(i);d(i);e(i);}}});var c=function(i){WebLight.each(a.boundControls,function(m,l,j){if(m.getEl){var k=m.getEl();
if(k&&k.mask&&k.isMasked&&!k.isMasked()){k.mask(i,"x-mask-loading");}}},a);};var g=function(){WebLight.each(a.boundControls,function(l,k,i){if(l.getEl){var j=l.getEl();
if(j&&j.unmask){j.unmask();}}},a);};this.on("beforeload",function(){c(Ext.LoadMask.prototype.msg);},this);
this.on("load",function(){a.selectedIndex(a.selectedIndex());g();});this.on("beforesubmit",function(){c("Saving");
});this.on("submit",function(){g();});f.on("datachanged",function(){f._columnSummaryRelations=null;f.clearComputedFieldSettings();
f._rowSummaryRelations=null;f.changes=[];setTimeout(function(){f.each(function(i){h(i);d(i);});e();},100);
});},bindControl:function(a){if(this.boundControls.indexOf(a)<0){this.boundControls.push(a);}},unbindControl:function(a){if(this.boundControls.indexOf(a)>=0){this.boundControls.remove(a);
}},getChangedRecords:function(){return this.changes||[];},rejectChanges:function(){WebLight.data.Store.superclass.rejectChanges.call(this);
this.changes=[];},load:function(a){if(!this.trackingChanges||this.changes.length==0){return WebLight.data.Store.superclass.load.call(this,a);
}else{Ext.MessageBox.confirm("Confirm",discardMessage,function(b){if(b=="yes"){return WebLight.data.Store.superclass.load.call(this,a);
}},this);}return false;},newRecord:function(c){var a=this;if(!WebLight.isDefined(this.recordType)){alert("record Type not defined");
return null;}var b=null;if(a.idProperty&&c&&c[a.idProperty]){b=c[a.idProperty];}return new this.recordType(Ext.apply(c||{},{_sysStatus:1}),b);
},isNewRecord:function(a){return a.get("_sysStatus")==1;},selectedIndex:function(){if(!this._selectedIndex){this._selectedIndex=0;
}if(!arguments||arguments.length==0){return this._selectedIndex;}var a=arguments[0];if(a<0){a=0;}if(this._selectedIndex!=a||this._selectedIndex>=this.getCount()){if(this.getCount()==0){this._selectedIndex=-1;
}else{this._selectedIndex=a;}if(this._selectedIndex>=this.getCount()){this._selectedIndex=0;}}this.fireEvent("selectedIndexChanged",this,this._selectedIndex);
return this;},_rowSummaryRelations:null,addRowRelations:function(c,a,f,g){var e=this;if(c=="sum"){if(e._rowSummaryRelations==null){e._rowSummaryRelations=[];
}var d=a;if(!WebLight.isArray(a)){d=[a];}var b=false;WebLight.each(e._rowSummaryRelations,function(i,h){if(i[0]==f){i[2]=i[2].concat(d).unique();
b=true;return true;}});if(!b){e._rowSummaryRelations.push([f,g,d]);}}return e;},_computedFields:null,clearComputedFieldSettings:function(){var a=this;
a._computedFields=null;},setComputedField:function(b,a,d){var c=this;if(c._computedFields==null){c._computedFields=[];
}WebLight.each(c._computedFields,function(f,e){if(f[0]==b){c._computedFields.remove(f);return true;}});
c._computedFields.push([b,a,d]);},_columnSummaryRelations:null,addColumnRelations:function(c,a,e){var b=this;
if(c=="sum"){if(b._columnSummaryRelations==null){b._columnSummaryRelations=[];}var d=a;if(!WebLight.isArray(a)){d=[a];
}b._columnSummaryRelations.push([e,d]);}}});WebLight.data.JsonHttpProxy=Ext.extend(Ext.data.HttpProxy,{doRequest:function(d,a,b,e,g,f,c){b=b||{};
delete b.jsonData;b.jsonData=Ext.apply({},b);WebLight.data.JsonHttpProxy.superclass.doRequest.call(this,d,a,b,e,g,f,c);
}});WebLight.data.JsonReader=Ext.extend(Ext.data.JsonReader,{read:function(d){var c=d.responseText;var a=Ext.decode(c);
if(a&&a.status==200){return this.readRecords(a.result);}else{if(a&&a.status==401){WebLight.PageMgr.fireEvent("accessDenied");
return this.readRecords({totalRecords:0,data:[]});}else{var b=a.result.message;if(!b){b="Unknown error! Failed to load data.";
}alert(b);return this.readRecords({totalRecords:0,data:[]});}}}});WebLight.data.JsonStore=Ext.extend(WebLight.data.Store,{otype:"",constructor:function(b){b=b||{};
Ext.apply(b,{root:"data",totalProperty:"totalRecords"});var c=this;if(b.otype){if(!b.readUrl){b.readUrl="/weblight.aspx/load";
}if(!b.saveUrl){b.saveUrl="/weblight.aspx/save";}}if(b.readUrl){var a=new WebLight.data.JsonHttpProxy({url:b.readUrl});
Ext.applyIf(b,{proxy:a,remoteSort:true});}this.paramNames={start:"start",limit:"limit",sort:"sort",dir:"dir"};
Ext.apply(b,{reader:new WebLight.data.JsonReader(b,b.recordType)});WebLight.data.JsonStore.superclass.constructor.call(this,b);
this.queryable=new WebLight.data.Queryable({store:this,recordType:b.recordType});this.setBaseParam("_sysName",b.otype);
},exportToExcel:function(b,c,f){b=Ext.apply({},b);if(this.sortInfo&&this.remoteSort){var d=this.paramNames;
b.params=Ext.apply({},b.params);b.params[d.sort]=this.sortInfo.field;b.params[d.dir]=this.sortInfo.direction;
}b=Ext.applyIf(b||{},{params:{}});var e=[];Ext.each(c,function(h,g){if(WebLight.isString(h)){e.push({field:h});
}else{e.push(h);}});Ext.applyIf(b.params,this.baseParams);if(this.baseParams._properties){Ext.apply(b.params,{_properties:this.baseParams._properties});
}data=jQuery.param({query:Ext.encode(b.params),fields:Ext.encode(e),fileName:f||"export.csv"});var a="";
Ext.each(data.split("&"),function(g){var h=g.split("=");a+='<input type="hidden" name="'+h[0]+'" value="'+h[1]+'" />';
});jQuery('<form target="_blank" action="'+WebLight.getProxyUrl("__generic","exportToExcel")+'" method="post">'+a+"</form>").appendTo("body").submit().remove();
},submitChanges:function(d,e){this.fireEvent("beforesubmit",this);var b=this;var f=function(g){var i=[];
var h=[];Ext.each(g,function(j){if(h.indexOf(j)==-1){i.push(Ext.apply(j.data,{_sysName:b.otype}));h.push(j);
}});return i;};var c=f(this.changes);if(c.length==0){if(d){d({affectedCount:0,data:[]});}b.fireEvent("submit",this);
}else{var a=this;WebLight.wcfPost(this.saveUrl,Ext.encode({changes:c}),function(h){if(h){if(h.status==401){WebLight.PageMgr.fireEvent("accessDenied");
}if(h.status==200){this.changes=[];if(d){d(h.result);}}else{var g=h.result.message;if(!g){g="Unknown error! Failed to load data.";
}if(e){e(h.status,g);}}}b.fireEvent("submit",this);},function(g){if(e){e(500,g.responseText);}b.fireEvent("submit",this);
});}return this;}});WebLight.data.PagingMemoryProxy=Ext.extend(Ext.data.MemoryProxy,{constructor:function(a){WebLight.data.PagingMemoryProxy.superclass.constructor.call(this);
this.data=a;},doRequest:function(f,a,c,h,d,k,g){c=c||{};var j;try{j=h.readRecords(this.data);}catch(i){this.fireEvent("loadexception",this,g,null,i);
d.call(k,null,g,false);return;}if(c.filter!==undefined){j.records=j.records.filter(function(e){if(typeof(e)=="object"){var m=c.filterCol||0;
return String(e.data[m]).match(c.filter)?true:false;}else{return String(e).match(c.filter)?true:false;
}});j.totalRecords=j.records.length;}if(c.sort!==undefined){var l=String(c.dir).toUpperCase()=="DESC"?-1:1;
var b=function(e,m){return e>m?1:(e<m?-1:0);};j.records.sort(function(e,m){var n=0;if(typeof(e)=="object"){n=b(e.data[c.sort],m.data[c.sort])*l;
}else{n=b(e,m)*l;}if(n==0){n=(e.index<m.index?-1:1);}return n;});}if(c.start!==undefined&&c.limit!==undefined){j.records=j.records.slice(c.start,c.start+c.limit);
}d.call(k,j,g,true);}});WebLight.Router=(function(){var a=[];var d=[];var b=null;var e="/";var c=function(g){var f=null;
$.each(a,function(o,h){var l=new RegExp(h,"gi");if(match=l.exec(g)){var k=null;if(WebLight.isFunction(d[o])){k=d[o](g,match);
}else{var k=WebLight.apply({},d[o]);var n=WebLight.encode(k);for(var j=0;j<match.length-1;j++){var m=new RegExp("\\{"+j+"\\}","gm");
n=n.replace(m,match[j+1]);}WebLight.apply(k,WebLight.decode(n));}if(b&&b.renderTo&&(!k.renderTo||k.renderTo=="")){k.renderTo=b.renderTo;
}if(!k.id){k.id=k.xtype;}f=WebLight.PageMgr.load(g,k);return false;}});if(null!=f){e=g;}return f;};return{init:function(f){b=f;
$.historyInit(function(g){if(g){c.defer(200,this,[g]);}});if(location.hash.replace(/\?.*$/,"")==""){if(f.defaultUrl){WebLight.Router.route(f.defaultUrl);
}else{if(f.dashboard){WebLight.Router.route(f.dashboard);}}}},mapRoute:function(pattern,f){a.push(pattern);
d.push(f);},route:function(url,g){url=url.trim();if(url.endsWith("/")){url=url.substr(0,url.length-1);
}if(url.startsWith("/")){url=url.substr(1);}else{var h=e.substr(0,e.lastIndexOf("/"));while(url.substr(0,3)=="../"){h=h.substr(0,h.lastIndexOf("/"));
url=url.substr(3);}url=h+"/"+url;}var f=c(url);if(null!=f){$.historyLoad(url);if(g){g(f);}}return f;}};
})();WebLight.Control=Ext.extend(WebLight.util.Observable,{childControlsCreated:false,renderTo:"",html:null,$this:null,constructor:function(a){var b=this;
WebLight.Control.superclass.constructor.call(this,a);Ext.apply(this,a);if(!b.id){b.id="wl_ctrl_"+WebLight.Control.globalSequenceId++;
}b._controls=[];b._regControls=[];b.$this=$('<div id="'+b.id+'" style="display:none"></div>').appendTo(document.body);
b.loadTemplate(b.html,b.$this);b.childControlsCreated=false;b.rendered=false;b.addEvents("render","hibernate","resume","destroy","refresh");
},loadTemplate:function(b,c){var a=this;if(b){c=c||a.$this;if(WebLight.isString(c)&&c.substr(0,1)!="#"){c="#"+c;
}$(b.replace(/id=\"/gi,'id="'+a.id+"_").replace(/href=\"\#(?=[a-zA-Z])/gi,'href="#'+a.id+"_")).appendTo($(c));
}},ensureChildControls:function(){var a=this;if(a.childControlsCreated){return a;}a.createChildControls();
},$child:function(a){return jQuery("#"+this.getClientId(a));},$find:function(a){var b=this;return jQuery(a,b.$this);
},getClientId:function(a){return String.format("{0}_{1}",this.id,a);},createChildControls:function(){var a=this;
a.childControlsCreated=true;},addChildControl:function(b,c){var a=this;if(c){b.containerId=c;}a._controls.push(b);
if(a.rendered){if(b.containerId){b.render(a.getClientId(b.containerId));}else{b.render(a.$this);}}},registerControl:function(a){var b=this;
if(b._controls.indexOf(a)>=0){return b;}if(b._regControls.indexOf(a)==-1){b._regControls.push(a);}return b;
},dataBind:function(){},renderChildControls:function(){var a=this;WebLight.each(a._controls,function(d,c,b){if(d.containerId){d.render(a.getClientId(d.containerId));
}else{d.render(a.$this);}},a);},doLayout:function(){var a=this;WebLight.each(this._controls,function(d,c,b){if(d.doLayout){d.doLayout();
}},a);},render:function(b){var a=this;var c=WebLight.isDefined(b)||a.renderTo!=b;if(WebLight.isDefined(b)&&a.renderTo!=b){this.renderTo=b;
}if(c){if(WebLight.isString(a.renderTo)){a.$this.appendTo("#"+a.renderTo);}else{a.$this.appendTo(a.renderTo);
}}if(a.rendered){return;}a.ensureChildControls();$(a.$this).show();a.renderChildControls();a.dataBind();
a.rendered=true;a.fireEvent("render",a);},resume:function(){var a=this;a.fireEvent("resume",a);WebLight.each(a._controls,function(d,c,b){if(d.resume){d.resume();
}},a);$(a.$this).show();return a;},_unload:function(){var b=this;var a=true;WebLight.each(b._controls,function(e,d,c){if(WebLight.isFunction(e._unload)&&!e._unload()){a=false;
return false;}},b);if(!a){return false;}WebLight.each(b._regControls,function(e,d,c){if(WebLight.isFunction(e._unload)&&!e._unload()){a=false;
return false;}},b);if(!a){return false;}return b.fireEvent("beforeunload");},hibernate:function(){var a=this;
$(a.$this).hide();a.fireEvent("hibernate",a);WebLight.each(a._controls,function(d,c,b){if(d.hibernate){d.hibernate();
}},a);return a;},destroy:function(){var a=this;a.fireEvent("destroy",this);if(a.$this){a.$this.remove();
}a.$this=null;}});WebLight.Control.globalSequenceId=100;WebLight.override(WebLight.Control,{getEl:function(){return Ext.get(this.id);
},grouping:function(h,c){var i=this;if(!c){c={};}var g=function(k,m){if(k&&k.getEl){var l=k.getEl();if(l.isMasked&&!l.isMasked()){l.mask(m);
}}};var a=function(l){if(l&&l.getEl){var k=l.getEl();if(k){k.unmask();}}};var e=[];var b=[];Ext.each(h,function(l,k){if(l.getEl){e.push(l);
}else{if(l.getTotalCount){b.push(l);}}});var d=[];var f=function(m,l,k){if(d.length==0){if(!k||k()!==false){Ext.each(e,function(n,o){g(n,l);
});}}d.push(m);};var j=function(l,k){d.remove(l);if(d.length==0){(function(){if(d.length==0){if(k){k();
}Ext.each(e,function(m,n){a(m);});}}).defer(200);}};Ext.each(b,function(l,k){l.on("beforeload",function(){f(l,"Loading...",c.beforeload);
});l.on("beforesubmit",function(){f(l,"Saving...",c.beforesubmit);});l.on("load",function(){j(l,c.load);
});l.on("submit",function(){j(l,c.submit);});});}});WebLight.Control.ExtjsWrapper=function(b,a){a=WebLight.apply({xtype:"box",autoEl:{tag:"div"},listeners:{render:function(){var c=$("#"+this.id+" .x-panel-body");
if(c&&c.length){b.render(c);}else{b.render(this.id);}}}},a);return new Ext.create(a);};WebLight.Page=Ext.extend(WebLight.Control,{cacheable:false,title:"Untitled",constructor:function(a){WebLight.Page.superclass.constructor.call(this,a);
Ext.apply(this,a);this.isActive=false;},render:function(a){WebLight.Page.superclass.render.call(this,a);
if(document.title!=this.title){document.title=this.title;}$(window).bind("resize",this.doLayout);this.isActive=true;
},hibernate:function(){WebLight.Page.superclass.hibernate.call(this);$(window).unbind("resize",this.doLayout);
this.isActive=false;return this;},resume:function(){WebLight.Page.superclass.resume.call(this);$(window).bind("resize",this.doLayout);
this.setTitle(this.title);this.isActive=true;return this;},setTitle:function(a){if(a){this.title=a;}document.title=this.title;
return this;}});WebLight.PageMgr=function(){var b=new WebLight.util.MixedCollection();var a={};var c=WebLight.extend(WebLight.util.Observable,{constructor:function(d){c.superclass.constructor.call(this,d);
this.addEvents("load","resume","hibernate");},registerType:function(d,e){if(undefined!=a[d]&&a[d]!=e){alert("page xtype mapping conflict. xtype is "+d);
return;}a[d]=e;e.xtype=d;},isRegistered:function(d){return a[d]!==undefined;},create:function(d,e){return d.render?d:new a[d.xtype||e](d);
},getCurrentPage:function(){return b.last();},load:function(g,d,i){var f=null;var h=b.last();var e=function(){if(!h){return true;
}if(!h._unload()){return false;}if(h.cacheable&&h.id){h.hibernate();WebLight.PageMgr.fireEvent("hibernate",g,h);
}else{b.remove(h);h.destroy();delete h;h=null;}return true;};if(d.id){f=b.get(d.id);if(f){if(!f.isActive){if(!e()){return null;
}b.remove(f);b.add(f);f.resume();this.fireEvent("resume",g,f);}else{f.fireEvent("refresh",f);}return f;
}}if(!e()){return null;}f=WebLight.PageMgr.create(d,i);b.add(f);f.render();this.fireEvent("load",g,f);
return f;}});return new c();}();WebLight.form.FormPanel=Ext.extend(Ext.form.FormPanel,{initComponent:function(){this.addEvents("bound","storechanged");
var d=this;WebLight.form.FormPanel.superclass.initComponent.call(this);this._fields=new Ext.util.MixedCollection();
var a=function(f){d.boundRecord=f;d.form.loadRecord(f?f:{data:{}});if(f){d.fireEvent("bound",f);}};var b=function(g){if(d.boundRecord&&g.name){var f=g.getValue();
if(Ext.isArray(f)){var h=[];Ext.each(f,function(i){h.push(i.name);});f=h;}else{if(Ext.isObject(f)){if(f.inputValue){f=f.inputValue;
}}}d.boundRecord.set(g.name,f);}};var c=function(g){g.on({scope:d,change:function(h){if(!this.boundRecord&&this.store){var f=this.store.newRecord();
this.store.add(f);a(f);}b(h);}});};this.getForm().items.each(function(g){if(g.name){this._fields.add(g.name,g);
c(g);}if(g.xtype=="compositefield"||g.xtype=="checkboxgroup"){g.on("render",function(){g.items.each(function(f){if(f.name){d._fields.add(f.name,f);
c(f);}});});}else{if(g.xtype=="displayfield"){if(!g.fieldLabel||g.fieldLabel==""){g.on("render",function(){g.el.up(".x-form-item",10,true).addClass("no-field-label");
},g);}}}},this);var e=function(f){if(f.bindControl){f.bindControl(d);}f.on("beforesubmit",function(){if(!d.boundRecord){return;
}if(d.store.indexOf(d.boundRecord)==-1){d.store.add(d.boundRecord);}d._fields.each(function(h,g,i){if(h.xtype!="displayfield"){b(h);
}},d);},this);if(f.getCount()>0){if(f.selectedIndex){a(f.getAt(f.selectedIndex()));}else{a(f.getAt(0));
}}f.on("selectedIndexChanged",function(){if(f.selectedIndex){a(f.getAt(f.selectedIndex()));}else{a(f.getAt(0));
}});};if(this.store){e(this.store);}this.on("storechanged",function(f,g){e(f);if(g&&g.unbindControl){g.unbindControl(d);
}});},getBoundRecord:function(){return this.boundRecord;},getFieldByName:function(a){if(this._fields&&this._fields.containsKey(a)){return this._fields.get(a);
}return null;},getFieldValue:function(a){if(this._fields&&this._fields.containsKey(a)){return this._fields.get(a).getValue();
}return null;},getFieldValues:function(){var a={};this.getForm().items.each(function(b){if(b.xtype=="checkboxgroup"){if(b.name){a[b.name]=b.getValue();
}else{b.items.each(function(c){if(c.name){a[c.name]=c.getValue();}});}}else{if(b.xtype=="compositefield"){b.items.each(function(c){if(c.name&&c.xtype!="displayfield"){a[c.name]=c.getValue();
}});}else{if(b.name&&b.xtype!="displayfield"){a[b.name]=b.getValue();}}}},this);return a;},bindStore:function(b){if(b!=this.store){var a=this.store;
this.store=b;this.fireEvent("storechanged",b,a);}},reset:function(){if(this.boundRecord){this.boundRecord.reject();
this.form.loadRecord(this.boundRecord);}else{this.getForm().items.each(function(a){a.reset();},this);
this.getForm().reset();}}});WebLight.form.ComboBox=Ext.extend(Ext.form.ComboBox,{initComponent:function(){var a=this;
if(!this.displayField||this.displayField==""){this.displayField="value";}if(!this.valueField||this.valueField==""){this.valueField="key";
}if(this.store){this.store.on("load",function(c,b){this.clearValue();Ext.each(b,function(e,d){if(e.get(a.valueField)==a.innerValue){a.setValue(a.innerValue);
}});},this);}WebLight.form.ComboBox.superclass.initComponent.call(this);},setValue:function(b){var a=this.value;
this.innerValue=b;WebLight.form.ComboBox.superclass.setValue.call(this,b);if(a!=b){this.fireEvent("valuechange",b,this.getRawValue());
}return this;},filterFieldName:null,linkTo:function(a,b,c){a.on("valuechange",function(d){this.clearValue();
if(!d||d==""){this.store.removeAll();return;}var e={field:b||a.valueField,data:{type:c||"string",value:d}};
if(!this.store.baseParams){this.store.baseParams={};}if(!this.store.baseParams.filters){this.store.baseParams.filters=[];
}var f=false;Ext.each(this.store.baseParams.filters,function(g){if(g.field.toLowerCase()==e.field.toLowerCase()){g.data.value=d;
f=true;}});if(!f){this.store.baseParams.filters.push(e);}this.store.load();},this);}});WebLight.form.FormView=WebLight.extend(WebLight.Control,{constructor:function(d){var j=this;
j.addEvents("bound","storechanged");j._fields=new Ext.util.MixedCollection();var g=function(p){if(Ext.isArray(p)){for(var m=0,n=p.length;
m<n;m++){var o=p[m];var l=j.findField(o.name);if(l){l.setValue(o.value);}}}else{j._fields.each(function(s,r,u){var q=p[s.name];
s.setRawValue(q||"");},j);}};var b=function(m,l,n){if(l==j.boundRecord&&n==Ext.data.Record.EDIT){g(l?l.data:{});
}};var i=function(){if(j.boundRecord){g(j.boundRecord.data);}};var a=function(l){j.boundRecord=l;g(l?l.data:{});
if(l){j.fireEvent("bound",l);}};var e=function(n,l){if(j.boundRecord&&n){if(Ext.isArray(l)){var m=[];
Ext.each(l,function(o){m.push(n);});l=m;}else{if(Ext.isObject(l)){if(l.inputValue){l=l.inputValue;}}}j.boundRecord.set(n,l);
}};var h=function(l){e(l.name,l.getValue());};var c=function(l){l.on({scope:j,change:function(o){if(!j.boundRecord&&j.store){var m=o.getValue();
var n=j.store.newRecord();j.store.add(n);a(n);e(o.name,m);}else{h(o);}}});};var f=function(l){if(l.name){j._fields.add(l.name,l);
c(l);}if(l.xtype=="compositefield"||l.xtype=="checkboxgroup"){l.on("render",function(){l.items.each(function(m){if(m.name){j._fields.add(m.name,m);
c(m);}});});}};j.initField=f;var k=function(l){if(l.bindControl){l.bindControl(j);}l.on("update",b);l.on("beforesubmit",function(){if(!j.boundRecord){return;
}if(j.store.indexOf(j.boundRecord)==-1){j.store.add(j.boundRecord);}j._fields.each(function(n,m,o){if(n.xtype!="displayfield"){h(n);
}},j);},this);if(l.getCount()>0){if(l.selectedIndex){a(l.getAt(l.selectedIndex()));}else{a(l.getAt(0));
}}l.on("selectedIndexChanged",function(){if(l.selectedIndex){if(l.selectedIndex()==-1){a(null);}else{a(l.getAt(l.selectedIndex()));
}}else{a(l.getAt(0));}});};WebLight.form.FormView.superclass.constructor.call(this,d);if(j.items){WebLight.each(j.items,function(m,l){ctrl=m;
if(!ctrl.events){ctrl=j.createComponent(m);}j.addChildControl(ctrl,ctrl.name);});}if(d.store){k(d.store);
}j.on("storechanged",function(l,m){k(l);if(m&&m.unbindControl){m.unbindControl(j);m.un("update",b);}});
j.on("render",function(){i();});},loadTemplate:function(d,h){var f=this;if(f._container!=h){WebLight.form.FormView.superclass.loadTemplate.call(f,d,h);
return;}var i=new RegExp("{.*?}","gi");var c;var g=d;var a=[];this.cmpIndex=0;while(c=i.exec(g)){var b=Ext.decode(c[0]);
if(!b.name){b.name=String.format("{0}",this.cmpIndex++);}var e=String.format('<span id="{0}"></span>',b.name);
g=g.replace(c[0],e);a.push(b);}WebLight.form.FormView.superclass.loadTemplate.call(this,g,h);Ext.each(a,function(k,j){f.addChildControl(Ext.create(k),k.name);
});},applyDefaults:function(b){var a=this.defaults;if(a){if(Ext.isFunction(a)){a=a.call(this,b);}if(Ext.isString(b)){b=Ext.ComponentMgr.get(b);
Ext.apply(b,a);}else{if(!b.events){Ext.applyIf(b,a);}else{Ext.apply(b,a);}}}return b;},createComponent:function(d,a){if(d.render){return d;
}var b=Ext.create(d,a||this.defaultType);return b;},addChildControl:function(b,c){var a=this;WebLight.form.FormView.superclass.addChildControl.call(this,b,c);
if(a.isField(b)){a.initField(b);}return a;},addField:function(a){if(this.isField(a)){this.addChildControl(a,a.name);
}},findField:function(a){if(this._fields&&this._fields.containsKey(a)){return this._fields.get(a);}return null;
},bindStore:function(b){if(b!=this.store){var a=this.store;this.store=b;this.fireEvent("storechanged",b,a);
}return this;},getFieldByName:function(a){if(this._fields&&this._fields.containsKey(a)){return this._fields.get(a);
}return null;},isField:function(a){return !!a.name&&!!a.setValue&&!!a.getValue&&!!a.markInvalid&&!!a.clearInvalid;
}});WebLight.form.RangeField=WebLight.extend(Ext.form.Field,{defaultAutoCreate:{tag:"input",type:"hidden"},separator:"|",getStartConfig:function(){},getEndConfig:function(){},initComponent:function(){WebLight.form.RangeField.superclass.initComponent.call(this);
var a=WebLight.apply({id:this.id+"-start",selectOnFocus:this.selectOnFocus,validator:this.dateValidator,listeners:{blur:{scope:this,fn:this.onBlur},focus:{scope:this,fn:this.onFocus}}},this.getStartConfig(),this.startConfig);
this.sf=Ext.create(a);this.sf.ownerCt=this;var b=WebLight.apply({id:this.id+"-end",selectOnFocus:this.selectOnFocus,validator:this.dateValidator,listeners:{blur:{scope:this,fn:this.onBlur},focus:{scope:this,fn:this.onFocus}}},this.getEndConfig(),this.endConfig);
this.ef=Ext.create(b);this.ef.ownerCt=this;this.relayEvents(this.sf,["focus","specialkey","invalid","valid"]);
this.relayEvents(this.ef,["focus","specialkey","invalid","valid"]);},onRender:function(b,a){if(this.isRendered){return;
}WebLight.form.RangeField.superclass.onRender.call(this,b,a);t=Ext.DomHelper.append(b,{tag:"table",style:"border-collapse:collapse",children:[{tag:"tr",children:[{tag:"td",style:"padding-right:4px",cls:"ux-rangefield-start"},{tag:"td",cls:"ux-rangefield-end"}]}]},true);
this.tableEl=t;this.wrap=t.wrap({cls:"x-form-field-wrap"});this.wrap.on("mousedown",this.onMouseDown,this,{delay:10});
this.sf.render(t.child("td.ux-rangefield-start"));this.ef.render(t.child("td.ux-rangefield-end"));this.on("specialkey",this.onSpecialKey,this);
this.sf.el.swallowEvent(["keydown","keypress"]);this.ef.el.swallowEvent(["keydown","keypress"]);if("side"===this.msgTarget){var d=this.el.findParent(".x-form-element",10,true);
this.errorIcon=d.createChild({cls:"x-form-invalid-icon"});var c={errorIcon:this.errorIcon,msgTarget:"side",alignErrorIcon:this.alignErrorIcon.createDelegate(this)};
Ext.apply(this.sf,c);Ext.apply(this.ef,c);}this.el.dom.name=this.hiddenName||this.name||this.id;this.sf.el.dom.removeAttribute("name");
this.ef.el.dom.removeAttribute("name");this.isRendered=true;this.updateHidden();},adjustSize:Ext.BoxComponent.prototype.adjustSize,alignErrorIcon:function(){this.errorIcon.alignTo(this.tableEl,"tl-tr",[2,0]);
},clearInvalid:function(){this.sf.clearInvalid();this.ef.clearInvalid();},markInvalid:function(a){this.sf.markInvalid(a);
this.ef.markInvalid(a);},beforeDestroy:function(){if(this.isRendered){this.wrap.removeAllListeners();
this.wrap.remove();this.tableEl.remove();this.sf.destroy();this.ef.destroy();}},disable:function(){if(this.isRendered){this.sf.disabled=this.disabled;
this.sf.onDisable();this.ef.onDisable();}this.disabled=true;this.sf.disabled=true;this.ef.disabled=true;
this.fireEvent("disable",this);return this;},enable:function(){if(this.rendered){this.sf.onEnable();this.ef.onEnable();
}this.disabled=false;this.sf.disabled=false;this.ef.disabled=false;this.fireEvent("enable",this);return this;
},focus:function(){this.sf.focus();},getPositionEl:function(){return this.wrap;},getResizeEl:function(){return this.wrap;
},getValue:function(){var b=this.sf.getValue();if(b instanceof Date){b=Ext.util.Format.date(b,this.dateFormat||"m/d/Y");
}if(!b){b="";}var a=this.ef.getValue();if(a instanceof Date){a=Ext.util.Format.date(a,this.dateFormat||"m/d/Y");
}if(!a){a="";}return String.format("{0}{1}{2}",b,this.separator,a);},isValid:function(){return this.sf.isValid()&&this.ef.isValid();
},isVisible:function(){return this.sf.rendered&&this.sf.getActionEl().isVisible();},onBlur:function(a){if(this.wrapClick){a.focus();
this.wrapClick=false;}this.updateHidden();(function(){if(!this.sf.hasFocus&&!this.ef.hasFocus){var b=this.getValue();
if(String(b)!==String(this.originalValue)){this.fireEvent("change",this,b,this.originalValue);}this.hasFocus=false;
this.fireEvent("blur",this);}}).defer(100,this);},onFocus:function(){if(!this.hasFocus){this.hasFocus=true;
this.originalValue=this.getValue();this.fireEvent("focus",this);}},onMouseDown:function(a){if(!this.disabled){this.wrapClick="td"===a.target.nodeName.toLowerCase();
}},onSpecialKey:function(b,c){var a=c.getKey();if(a===c.TAB){if(b===this.sf&&!c.shiftKey){c.stopEvent();
this.ef.focus();}if(b===this.ef&&c.shiftKey){c.stopEvent();this.sf.focus();}}if(a===c.ENTER){this.updateValue();
}},reset:function(){this.sf.reset();this.ef.reset();},setSize:function(b,a){if(!b){return;}fw=(b-4)/2;
this.sf.setSize(fw,a);this.ef.setSize(fw,a);if(Ext.isIE){this.sf.el.up("td").setWidth(fw);this.ef.el.up("td").setWidth(fw);
}},setValue:function(a){if(!a){this.setValue("|");return;}var b=(String.format("{0}",a)).split(this.separator);
if(b[0]!=""){this.sf.setValue(b[0]);}if(b.length>1&&b[1]!=""){this.ef.setValue(b[1]);}this.updateHidden();
},setVisible:function(a){if(a){this.sf.show();this.ef.show();}else{this.sf.hide();this.ef.hide();}return this;
},show:function(){return this.setVisible(true);},hide:function(){return this.setVisible(false);},updateHidden:function(){if(this.isRendered){this.el.dom.value=this.getValue();
}},updateValue:function(){this.updateDate();this.updateTime();this.updateHidden();return;},validate:function(){return this.sf.validate()&&this.ef.validate();
},renderer:function(b){var c=b.editor.dateFormat||Ext.ux.form.DateTime.prototype.dateFormat;c+=" "+(b.editor.timeFormat||Ext.ux.form.DateTime.prototype.timeFormat);
var a=function(d){var e=Ext.util.Format.date(d,c);return e;};return a;}});Ext.reg("rangefield",WebLight.form.RangeField);
WebLight.grid.EditorColumnModel=Ext.extend(Ext.grid.ColumnModel,{_cachedEditor:null,constructor:function(a){this._cachedEditor=new Ext.util.MixedCollection();
WebLight.grid.EditorColumnModel.superclass.constructor.call(this,a);},createTextEditor:function(){var a={xtype:"textfield"};
if(arguments.length>0&&Ext.isObject(arguments[0])){Ext.apply(a,arguments[0]);}return this.createEditor(a);
},createEditor:function(d){if(!d||!Ext.isObject(d)){return null;}var b=function(g){var f=0;g.each(function(h){if(h.id&&h.id!=NaN){f+=h.id+1;
}else{f+=e(h.data).length+1;}});return f;};var e=function(g){var f=[];if(Ext.isArray(g)){Ext.each(g,function(i,h){f.push(e(i));
});}else{for(key in g){if(Ext.isString(g[key])||Ext.isNumber(g[key])){f.push(String.format("{0}={1}",key,g[key]));
}else{if(key=="store"){f.push(String.format("store={0}",b(g[key])));}}}}return f.join("");};var c=e(d);
var a=this._cachedEditor.get(c);if(!a){a=new Ext.grid.GridEditor(Ext.create(d));this._cachedEditor.add(c,a);
}return a;},createNumberEditor:function(){var a={xtype:"numberfield",selectOnFocus:true,decimalPrecision:2};
if(arguments.length>0&&Ext.isObject(arguments[0])){Ext.apply(a,arguments[0]);}return this.createEditor(a);
},createNumberRangeEditor:function(){var a={xtype:"rangefield",fieldType:"numberfield",dateFormat:"m/d/Y",selectOnFocus:true,startConfig:{xtype:"numberfield"},endConfig:{xtype:"numberfield"}};
if(arguments.length>0&&Ext.isObject(arguments[0])){Ext.apply(a,arguments[0]);}return this.createEditor(a);
},createCheckbox:function(){var a={xtype:"checkbox"};if(arguments.length>0&&Ext.isObject(arguments[0])){Ext.apply(a,arguments[0]);
}return this.createEditor(a);},createDateEditor:function(){var a={xtype:"datefield",format:"m/d/Y",selectOnFocus:true};
if(arguments.length>0&&Ext.isObject(arguments[0])){Ext.apply(a,arguments[0]);}return this.createEditor(a);
},createDateRangeEditor:function(){var a={xtype:"rangefield",fieldType:"datefield",dateFormat:"m/d/Y",selectOnFocus:true,startConfig:{xtype:"datefield"},endConfig:{xtype:"datefield"}};
if(arguments.length>0&&Ext.isObject(arguments[0])){Ext.apply(a,arguments[0]);}return this.createEditor(a);
},createComboBox:function(){var a={xtype:"combo",mode:"local",typeAhead:true,displayField:"value",valueField:"key",triggerAction:"all",selectOnFocus:true};
if(arguments.length>0&&Ext.isObject(arguments[0])){Ext.apply(a,arguments[0]);}return this.createEditor(a);
},isCellEditable:function(a,b){var c=this.getCellEditor(a,b);return Ext.isDefined(c)&&null!=c;}});Ext.reg("combo",WebLight.form.ComboBox);
WebLight.grid.GridPanel=Ext.extend(Ext.grid.GridPanel,{pageSize:-1,enableRowNumberer:false,initComponent:function(){var c=this;
var a=this;if(this.pageSize!=-1){this.pagingBar=new Ext.PagingToolbar({store:this.store,displayInfo:true,pageSize:this.pageSize,prependButtons:true,items:this.bbar});
this.bbar=this.pagingBar;if(this.store){this.store.setBaseParam(this.store.paramNames.limit,this.pageSize);
}}if(this.enableRowNumberer){this.rowBaseIndex=0;var b=this.columns||this.cm.columns;b=[{dataIndex:"",header:"",width:23,sortable:false,fixed:true,menuDisabled:true,renderer:function(f,g,e,d){return c.rowBaseIndex+d+1;
}}].concat(b);this.cm=new Ext.grid.ColumnModel({columns:b});if(this.store){this.store.on("beforeload",function(e,d){this.rowBaseIndex=d.params.start||0;
},this);}}this.addEvents("xcellclick");WebLight.grid.GridPanel.superclass.initComponent.call(this);this.on("cellclick",function(d,k,l,j){var i=j.getTarget();
var h=$(i).attr("xcmd");if(h){var f=d.getStore().getAt(k);this.fireEvent("xcellclick",this,h,f,k,l,j);
}},this);if(this.getSelectionModel().singleSelect){this.getSelectionModel().on("rowselect",function(f,d,e){if(c.store&&c.store.selectedIndex){c.store.selectedIndex(c.store.indexOf(e));
}},this);this.getSelectionModel().on("rowdeselect",function(f,d,e){if(c.store&&c.store.selectedIndex&&c.store.getAt(d)==f.getSelected()){c.store.selectedIndex(-1);
}},this);}a.on("render",function(){a.resizeHeaderDiv();a.getView().on("refresh",function(){a.resizeHeaderDiv();
});});},resizeHeaderDiv:function(){var a=$("#"+this.id).width();var b=$(".x-grid3-header-offset",$("#"+this.id)).width();
if(b<a){b=a-25;}$(".x-grid3-header",$("#"+this.id)).width(b);},getSelectedRecords:function(){if(this.disableSelection){return[];
}var a=this.getSelectionModel();if(!a.hasSelection()){return[];}return a.getSelections();},bindStore:function(d){var e=this;
var a=this;var b=a.getView();var c=function(f){if(b.ds){b.ds.un("load",b.onLoad,b);b.ds.un("datachanged",b.onDataChange,b);
b.ds.un("add",b.onAdd,b);b.ds.un("remove",b.onRemove,b);b.ds.un("update",b.onUpdate,b);b.ds.un("clear",b.onClear,b);
if(b.ds!==f&&b.ds.autoDestroy){b.ds.destroy();}}if(f){f.on({scope:b,load:b.onLoad,datachanged:b.onDataChange,add:b.onAdd,remove:b.onRemove,update:b.onUpdate,clear:b.onClear});
}b.ds=f;};if(d!=this.store){if(this.store&&this.store.unbindControl){this.store.unbindControl(e);}this.store=Ext.StoreMgr.lookup(d);
if(this.store.bindControl){this.store.bindControl(e);}this.store.on("beforeload",function(g,f){this.rowBaseIndex=f.params.start||0;
},this);if(this.pageSize!=-1){this.pagingBar.bindStore(d,true);this.store.setBaseParam(this.store.paramNames.limit,this.pageSize);
}c(d);this.fireEvent("storechanged",d);}},destroy:function(){var a=this;if(a.store&&a.store.unbindControl){a.store.unbindControl(a);
}WebLight.grid.GridPanel.superclass.destroy.call(this);},exportToExcel:function(){var a=this;if(!a.store||!a.store.exportToExcel||a.store.getTotalCount()==0){return;
}var b=a.getColumnModel().getColumnsBy(function(e,d){return !e.hidden&&e.dataIndex&&e.dataIndex.length>0;
});var c=[];Ext.each(b,function(e,d){c.push({field:e.dataIndex,header:e.header});});a.store.exportToExcel(null,c,String.format("{0}.csv",a.title));
} 
});

//fix createContextualFragment error in IE9

if ((typeof Range !== "undefined") && !Range.prototype.createContextualFragment) {
    Range.prototype.createContextualFragment = function (html) {
        var frag = document.createDocumentFragment(),
            div = document.createElement("div");
        frag.appendChild(div);
        div.outerHTML = html;
        return frag;
    };
}