_builtInTemplate_a3bcf709=['<?xml version="1.0" encoding="utf-8" ?><transmission>  <target id="iiAuthorization" requestId="1">    <authorization id="1">      <authorize id="41" path="\\crothall\\chimes\\fin\\Budgeting"></authorize>      <authorize id="42" path="\\crothall\\chimes\\fin\\Budgeting\\AnnualizedBudget"></authorize>      <authorize id="16059" path="\\crothall\\chimes\\fin\\Budgeting\\AnnualizedBudget\\Read"></authorize>      <authorize id="16060" path="\\crothall\\chimes\\fin\\Budgeting\\AnnualizedBudget\\Write"></authorize>      <authorize id="44" path="\\crothall\\chimes\\fin\\Budgeting\\AnnualProjections"></authorize>      <authorize id="16063" path="\\crothall\\chimes\\fin\\Budgeting\\AnnualProjections\\ByPeriod"></authorize>      <authorize id="16064" path="\\crothall\\chimes\\fin\\Budgeting\\AnnualProjections\\ByPeriod\\Read"></authorize>      <authorize id="16065" path="\\crothall\\chimes\\fin\\Budgeting\\AnnualProjections\\ByPeriod\\Write"></authorize>      <authorize id="16066" path="\\crothall\\chimes\\fin\\Budgeting\\AnnualProjections\\WORForecast"></authorize>      <authorize id="16067" path="\\crothall\\chimes\\fin\\Budgeting\\AnnualProjections\\WORForecast\\Read"></authorize>      <authorize id="16068" path="\\crothall\\chimes\\fin\\Budgeting\\AnnualProjections\\WORForecast\\Write"></authorize>      <authorize id="1213" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetAdministration"></authorize>      <authorize id="16069" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetAdministration\\AnnualInformation"></authorize>      <authorize id="16070" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetAdministration\\AnnualInformation\\Read"></authorize>      <authorize id="16071" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetAdministration\\AnnualInformation\\Write"></authorize>      <authorize id="16072" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetAdministration\\ApproveBudget"></authorize>      <authorize id="16073" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetAdministration\\ApproveBudget\\Approve"></authorize>      <authorize id="16074" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetAdministration\\ApproveBudget\\Read"></authorize>      <authorize id="16075" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetAdministration\\ApproveBudget\\Reject"></authorize>      <authorize id="16076" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetAdministration\\ApproveBudget\\Write"></authorize>      <authorize id="16077" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetAdministration\\DeleteBudget"></authorize>      <authorize id="16078" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetAdministration\\DeleteBudget\\Read"></authorize>      <authorize id="16079" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetAdministration\\DeleteBudget\\Write"></authorize>      <authorize id="16080" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetAdministration\\ExportBudget"></authorize>      <authorize id="16081" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetAdministration\\ExportBudget\\Read"></authorize>      <authorize id="16082" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetAdministration\\ExportBudget\\Write"></authorize>      <authorize id="43" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetSummary"></authorize>      <authorize id="16061" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetSummary\\Read"></authorize>      <authorize id="16062" path="\\crothall\\chimes\\fin\\Budgeting\\BudgetSummary\\Write"></authorize>    </authorization>  </target></transmission>','<div style="color: #FFF; background-color: #659A66; padding: 10px; margin: 0 0 10px;">    <table width="100%" class="ann-proj-table">        <tbody>            <tr>                <td style="width: 35px;" class="label">Site:</td>                <td style="width: 300px"><div id="house-code-holder"></div></td>                <td style="width: 35px;" class="label">Job:</td>                <td style="width: 160px"><div id="job-code-holder"></div></td>                <td style="width: 80px;" class="label">Fiscal Year:</td>                <td style="width: 100px"><div id="fiscal-year-holder"></div></td>                <td style="width: 80px;" class="label">Period:</td>                <td style="width: 100px"><div id="period-holder"></div></td>                <td>&nbsp;</td>            </tr>        </tbody>    </table></div><div style="padding: 0 5px">    <p style="float:left">        The current page is READONLY.</p>        <div style="float:right"><span id="load-button-holder"></span></div></div><div style="clear:both;height:1px;"></div><div id="transaction-summary-grid" style="padding: 10px 5px;"></div><br /><br />'];
/*
 * Ext JS Library 3.2.0
 * Copyright(c) 2006-2010 Ext JS, LLC
 * licensing@extjs.com
 * http://www.extjs.com/license
 */
Ext.ns("Ext.ux.grid");
Ext.ux.grid.ColumnHeaderGroup=Ext.extend(Ext.util.Observable,{_grid:null,constructor:function(a){this.config=a;
},refreshHeader:function(a){if(this._grid){this._grid.colModel.rows=[a];}},init:function(a){Ext.applyIf(a.colModel,this.config);
Ext.apply(a.getView(),this.viewConfig);this._grid=a;},viewConfig:{initTemplates:function(){this.constructor.prototype.initTemplates.apply(this,arguments);
var a=this.templates||{};if(!a.gcell){a.gcell=new Ext.XTemplate('<td class="x-grid3-hd x-grid3-gcell x-grid3-td-{id} ux-grid-hd-group-row-{row} {cls}" style="{style}">','<div {tooltip} class="x-grid3-hd-inner x-grid3-hd-{id}" unselectable="on" style="{istyle}">',this.grid.enableHdMenu?'<a class="x-grid3-hd-btn" href="#"></a>':"","{value}</div></td>");
}this.templates=a;this.hrowRe=new RegExp("ux-grid-hd-group-row-(\\d+)","");},renderHeaders:function(){var l=this.templates,n=[],e=this.cm,b=e.rows,c="width:"+this.getTotalWidth()+";";
for(var j=0,p=b.length;j<p;j++){var a=b[j],o=[];for(var h=0,g=0,f=a.length;h<f;h++){var k=a[h];k.colspan=k.colspan||1;
var m=this.getColumnId(k.dataIndex?e.findColumnIndex(k.dataIndex):g),d=Ext.ux.grid.ColumnHeaderGroup.prototype.getGroupStyle.call(this,k,g);
o[h]=l.gcell.apply({cls:"ux-grid-hd-group-cell",id:m,row:j,style:"width:"+d.width+";"+(d.hidden?"display:none;":"")+(k.align?"text-align:"+k.align+";":""),tooltip:k.tooltip?(Ext.QuickTips.isEnabled()?"ext:qtip":"title")+'="'+k.tooltip+'"':"",istyle:k.align=="right"?"padding-right:16px":"",btn:this.grid.enableHdMenu&&k.header,value:k.header||"&nbsp;"});
g+=k.colspan;}n[j]=l.header.apply({tstyle:c,cells:o.join("")});}n.push(this.constructor.prototype.renderHeaders.apply(this,arguments));
return n.join("");},onColumnWidthUpdated:function(){this.constructor.prototype.onColumnWidthUpdated.apply(this,arguments);
Ext.ux.grid.ColumnHeaderGroup.prototype.updateGroupStyles.call(this);},onAllColumnWidthsUpdated:function(){this.constructor.prototype.onAllColumnWidthsUpdated.apply(this,arguments);
Ext.ux.grid.ColumnHeaderGroup.prototype.updateGroupStyles.call(this);},onColumnHiddenUpdated:function(){this.constructor.prototype.onColumnHiddenUpdated.apply(this,arguments);
Ext.ux.grid.ColumnHeaderGroup.prototype.updateGroupStyles.call(this);},getHeaderCell:function(a){return this.mainHd.query(this.cellSelector)[a];
},findHeaderCell:function(a){return a?this.fly(a).findParent("td.x-grid3-hd",this.cellSelectorDepth):false;
},findHeaderIndex:function(a){var b=this.findHeaderCell(a);return b?this.getCellIndex(b):false;},updateSortIcon:function(b,a){var d=this.sortClasses,c=this.mainHd.select(this.cellSelector).removeClass(d);
c.item(b).addClass(d[a=="DESC"?1:0]);},handleHdDown:function(b,f){var a=Ext.get(f);if(a.hasClass("x-grid3-hd-btn")){b.stopEvent();
var g=this.findHeaderCell(f);Ext.fly(g).addClass("x-grid3-hd-menu-open");var c=this.getCellIndex(g);this.hdCtxIndex=c;
var d=this.hmenu.items,h=this.cm;d.get("asc").setDisabled(!h.isSortable(c));d.get("desc").setDisabled(!h.isSortable(c));
this.hmenu.on("hide",function(){Ext.fly(g).removeClass("x-grid3-hd-menu-open");},this,{single:true});
this.hmenu.show(f,"tl-bl?");}else{if(a.hasClass("ux-grid-hd-group-cell")||Ext.fly(f).up(".ux-grid-hd-group-cell")){b.stopEvent();
}}},handleHdMove:function(a,d){var h=this.findHeaderCell(this.activeHdRef);if(h&&!this.headersDisabled&&!Ext.fly(h).hasClass("ux-grid-hd-group-cell")){var g=this.splitHandleWidth||5,c=this.activeHdRegion,j=a.getPageX(),f=h.style,b="";
if(this.grid.enableColumnResize!==false){if(j-c.left<=g&&this.cm.isResizable(this.activeHdIndex-1)){b=Ext.isAir?"move":Ext.isWebKit?"e-resize":"col-resize";
}else{if(c.right-j<=(!this.activeHdBtn?g:2)&&this.cm.isResizable(this.activeHdIndex)){b=Ext.isAir?"move":Ext.isWebKit?"w-resize":"col-resize";
}}}f.cursor=b;}},handleHdOver:function(a,c){var d=this.findHeaderCell(c);if(d&&!this.headersDisabled){this.activeHdRef=c;
this.activeHdIndex=this.getCellIndex(d);var b=this.fly(d);this.activeHdRegion=b.getRegion();if(!(this.cm.isMenuDisabled(this.activeHdIndex)||b.hasClass("ux-grid-hd-group-cell"))){b.addClass("x-grid3-hd-over");
this.activeHdBtn=b.child(".x-grid3-hd-btn");if(this.activeHdBtn){this.activeHdBtn.dom.style.height=(d.firstChild.offsetHeight-1)+"px";
}}}},handleHdOut:function(a,b){var c=this.findHeaderCell(b);if(c&&(!Ext.isIE||!a.within(c,true))){this.activeHdRef=null;
this.fly(c).removeClass("x-grid3-hd-over");c.style.cursor="";}},handleHdMenuClick:function(e){var f=this.hdCtxIndex,m=this.cm,k=this.ds,n=e.getItemId();
switch(n){case"asc":k.sort(m.getDataIndex(f),"ASC");break;case"desc":k.sort(m.getDataIndex(f),"DESC");
break;default:if(n.substr(0,5)=="group"){var g=n.split("-"),s=parseInt(g[1],10),p=parseInt(g[2],10),a=this.cm.rows[s],l,q=0;
for(var g=0,d=a.length;g<d;g++){l=a[g];if(p>=q&&p<q+l.colspan){break;}q+=l.colspan;}if(e.checked){var o=m.getColumnsBy(this.isHideableColumn,this).length;
for(var g=q,d=q+l.colspan;g<d;g++){if(!m.isHidden(g)){o--;}}if(o<1){this.onDenyColumnHide();return false;
}}for(var g=q,d=q+l.colspan;g<d;g++){if(m.config[g].fixed!==true&&m.config[g].hideable!==false){m.setHidden(g,e.checked);
}}}else{f=m.getIndexById(n.substr(4));if(f!=-1){if(e.checked&&m.getColumnsBy(this.isHideableColumn,this).length<=1){this.onDenyColumnHide();
return false;}m.setHidden(f,e.checked);}}e.checked=!e.checked;if(e.menu){var c=function(r){r.items.each(function(t){if(!t.disabled){t.setChecked(e.checked,false);
if(t.menu){c(t.menu);}}});};c(e.menu);}var j=e,h;while(j=j.parentMenu){if(!j.parentMenu||!(h=j.parentMenu.items.get(j.getItemId()))||!h.setChecked){break;
}var b=j.items.findIndexBy(function(r){return r.checked;})>=0;h.setChecked(b,true);}e.checked=!e.checked;
}return true;},beforeColMenuShow:function(){var q=this.cm,j=this.cm.rows;this.colMenu.removeAll();for(var x=0,s=q.getColumnCount();
x<s;x++){var u=this.colMenu,k=q.getColumnHeader(x),a=[];if(q.config[x].fixed!==true&&q.config[x].hideable!==false){for(var m=0,g=j.length;
m<g;m++){var o=j[m],p,w=0;for(var v=0,d=o.length;v<d;v++){p=o[v];if(x>=w&&x<w+p.colspan){break;}w+=p.colspan;
}if(p&&p.header){if(q.hierarchicalColMenu){var t="group-"+m+"-"+w;var e=u.items.item(t);var l=e?e.menu:null;
if(!l){l=new Ext.menu.Menu({itemId:t});l.on("itemclick",this.handleHdMenuClick,this);var b=false,f=true;
for(var h=w,n=w+p.colspan;h<n;h++){if(!q.isHidden(h)){b=true;}if(q.config[h].hideable!==false){f=false;
}}u.add({itemId:t,text:p.header,menu:l,hideOnClick:false,checked:b,disabled:f});}u=l;}else{a.push(p.header);
}}}a.push(k);u.add(new Ext.menu.CheckItem({itemId:"col-"+q.getColumnId(x),text:a.join(" "),checked:!q.isHidden(x),hideOnClick:false,disabled:q.config[x].hideable===false}));
}}},renderUI:function(){this.constructor.prototype.renderUI.apply(this,arguments);Ext.apply(this.columnDrop,Ext.ux.grid.ColumnHeaderGroup.prototype.columnDropConfig);
Ext.apply(this.splitZone,Ext.ux.grid.ColumnHeaderGroup.prototype.splitZoneConfig);}},splitZoneConfig:{allowHeaderDrag:function(a){return !a.getTarget(null,null,true).hasClass("ux-grid-hd-group-cell");
}},columnDropConfig:{getTargetFromEvent:function(a){var b=Ext.lib.Event.getTarget(a);return this.view.findHeaderCell(b);
},positionIndicator:function(a,b,c){var f=Ext.ux.grid.ColumnHeaderGroup.prototype.getDragDropData.call(this,a,b,c);
if(f===false){return false;}var d=f.px+this.proxyOffsets[0];this.proxyTop.setLeftTop(d,f.r.top+this.proxyOffsets[1]);
this.proxyTop.show();this.proxyBottom.setLeftTop(d,f.r.bottom);this.proxyBottom.show();return f.pt;},onNodeDrop:function(A,D,s,x){var k=x.header;
if(k!=A){var q=Ext.ux.grid.ColumnHeaderGroup.prototype.getDragDropData.call(this,k,A,s);if(q===false){return false;
}var v=this.grid.colModel,m=q.oldIndex<q.newIndex,z=v.rows;for(var C=q.row,l=z.length;C<l;C++){var a=z[C],f=a.length,B=0,y=1,t=f;
for(var g=0,w=0;g<f;g++){var u=a[g];if(q.oldIndex>=w&&q.oldIndex<w+u.colspan){B=g;}if(q.oldIndex+q.colspan-1>=w&&q.oldIndex+q.colspan-1<w+u.colspan){y=g-B+1;
}if(q.newIndex>=w&&q.newIndex<w+u.colspan){t=g;}w+=u.colspan;}var b=a.splice(B,y);z[C]=a.splice(0,t-(m?y:0)).concat(b).concat(a);
}for(var o=0;o<q.colspan;o++){var p=q.oldIndex+(m?0:o),j=q.newIndex+(m?-1:o);v.moveColumn(p,j);this.grid.fireEvent("columnmove",p,j);
}return true;}return false;}},getGroupStyle:function(a,e){var f=0,g=true;for(var b=e,d=e+a.colspan;b<d;
b++){if(!this.cm.isHidden(b)){var c=this.cm.getColumnWidth(b);if(typeof c=="number"){f+=c;}g=false;}}return{width:(Ext.isBorderBox||(Ext.isWebKit&&!Ext.isSafari2)?f:Math.max(f-this.borderWidth,0))+"px",hidden:g};
},updateGroupStyles:function(k){var h=this.mainHd.query(".x-grid3-header-offset > table"),c=this.getTotalWidth(),a=this.cm.rows;
for(var f=0;f<h.length;f++){h[f].style.width=c;if(f<a.length){var j=h[f].firstChild.firstChild.childNodes;
for(var e=0,d=0;e<j.length;e++){var g=a[f][e];if((typeof k!="number")||(k>=d&&k<d+g.colspan)){var b=Ext.ux.grid.ColumnHeaderGroup.prototype.getGroupStyle.call(this,g,d);
j[e].style.width=b.width;j[e].style.display=b.hidden?"none":"";}d+=g.colspan;}}}},getGroupRowIndex:function(a){if(a){var b=a.className.match(this.hrowRe);
if(b&&b[1]){return parseInt(b[1],10);}}return this.cm.rows.length;},getGroupSpan:function(d,b){if(d<0){return{col:0,colspan:this.cm.getColumnCount()};
}var a=this.cm.rows[d];if(a){for(var c=0,f=0,e=a.length;c<e;c++){var g=a[c];if(b>=f&&b<f+g.colspan){return{col:f,colspan:g.colspan};
}f+=g.colspan;}return{col:f,colspan:0};}return{col:b,colspan:1};},getDragDropData:function(k,l,a){if(k.parentNode!=l.parentNode){return false;
}var g=this.grid.colModel,p=Ext.lib.Event.getPageX(a),c=Ext.lib.Dom.getRegion(l.firstChild),q,b;if((c.right-p)<=(c.right-c.left)/2){q=c.right+this.view.borderWidth;
b="after";}else{q=c.left;b="before";}var m=this.view.getCellIndex(k),d=this.view.getCellIndex(l);if(g.isFixed(d)){return false;
}var s=Ext.ux.grid.ColumnHeaderGroup.prototype.getGroupRowIndex.call(this.view,k),o=Ext.ux.grid.ColumnHeaderGroup.prototype.getGroupSpan.call(this.view,s,m),f=Ext.ux.grid.ColumnHeaderGroup.prototype.getGroupSpan.call(this.view,s,d),m=o.col;
d=f.col+(b=="after"?f.colspan:0);if(d>=o.col&&d<=o.col+o.colspan){return false;}var j=Ext.ux.grid.ColumnHeaderGroup.prototype.getGroupSpan.call(this.view,s-1,m);
if(d<j.col||d>j.col+j.colspan){return false;}return{r:c,px:q,pt:b,row:s,oldIndex:m,newIndex:d,colspan:o.colspan};
}});
/*
* Ext JS Library 3.0.0
* Copyright(c) 2006-2009 Ext JS, LLC
* licensing@extjs.com
* http://www.extjs.com/license
* 
* Modifications by Mykhail Stadnik <http://mikhailstadnik.com>:
*  - Nesting grids support added
*/
Ext.ns("Ext.grid");
Ext.grid.RowExpander=Ext.extend(Ext.util.Observable,{expandOnEnter:true,expandOnDblClick:true,header:"",width:20,sortable:false,fixed:true,menuDisabled:true,dataIndex:"",id:"expander",lazyRender:true,enableCaching:true,actAsTree:false,treeLeafProperty:"is_leaf",appendRowClass:true,alwaysAsLeaf:false,constructor:function(a){if(!a.id){a.id=Ext.id();
}Ext.apply(this,a);var b=".x-"+this.id+"-grid3-row-collapsed .x-grid3-row-expander { background-position:0 0; }.x-"+this.id+"-grid3-row-expanded .x-grid3-row-expander { background-position:-25px 0; }.x-"+this.id+"-grid3-row-collapsed .x-grid3-row-body { display:none !important; }.x-"+this.id+"-grid3-row-expanded .x-grid3-row-body { display:block !important; }.x-grid-expander-leaf .x-grid3-row-expander { background: none; }";
Ext.util.CSS.createStyleSheet(b,Ext.id());this.expanderClass="x-grid3-row-expander";this.rowExpandedClass="x-"+this.id+"-grid3-row-expanded";
this.rowCollapsedClass="x-"+this.id+"-grid3-row-collapsed";this.leafClass="x-grid-expander-leaf";this.addEvents({beforeexpand:true,expand:true,beforecollapse:true,collapse:true});
Ext.grid.RowExpander.superclass.constructor.call(this);if(this.tpl){if(typeof this.tpl=="string"){this.tpl=new Ext.Template(this.tpl);
}this.tpl.compile();}this.state={};this.bodyContent={};},getRowClass:function(d,c,b,a){b.cols=b.cols-1;
var f=this.bodyContent[d.id];if(!f&&!this.lazyRender){f=this.getBodyContent(d,c);}if(f){b.body=f;}var e=this.state[d.id]?this.rowExpandedClass:this.rowCollapsedClass;
if(this.alwaysAsLeaf||this.actAsTree&&d.get(this.treeLeafProperty)){e=this.leafClass;}return e;},init:function(b){this.grid=b;
var a=b.getView();a.getRowClass=this.getRowClass.createDelegate(this);a.enableRowBody=true;b.on("render",this.onRender,this);
b.on("destroy",this.onDestroy,this);a.on("beforerefresh",this.onBeforeRefresh,this);a.on("refresh",this.onRefresh,this);
},onRender:function(){var b=this.grid;var a=b.getView().mainBody;a&&a.on("mousedown",this.onMouseDown,this,{delegate:"."+this.expanderClass});
if(this.expandOnEnter){this.keyNav=new Ext.KeyNav(this.grid.getGridEl(),{enter:this.onEnter,scope:this});
}if(this.expandOnDblClick){b.on("rowdblclick",this.onRowDblClick,this);}if(this.actAsTree){b.getEl().swallowEvent(["mouseover","mouseout","mousedown","click","dblclick"]);
}},onBeforeRefresh:function(){var a=this.grid.getEl().select("."+this.rowExpandedClass);a.each(function(b){this.collapseRow(b.dom);
},this);},onRefresh:function(){var a=this.grid.getEl().select("."+this.rowExpandedClass);a.each(function(b){Ext.fly(b).replaceClass(this.rowExpandedClass,this.rowCollapsedClass);
},this);},onDestroy:function(){this.keyNav.disable();delete this.keyNav;var a=this.grid.getView().mainBody;
a&&a.un("mousedown",this.onMouseDown,this);},onRowDblClick:function(c,b,a){this.toggleRow(b);},onEnter:function(c){var a=this.grid;
var f=a.getSelectionModel();var b=f.getSelections();for(var d=0,h=b.length;d<h;d++){var j=a.getStore().indexOf(b[d]);
this.toggleRow(j);}},getBodyContent:function(a,b){if(!this.enableCaching){return this.tpl.apply(a.data);
}var c=this.bodyContent[a.id];if(!c){c=this.tpl.apply(a.data);this.bodyContent[a.id]=c;}return c;},onMouseDown:function(a,c){a.stopEvent();
var b=a.getTarget(".x-grid3-row");this.toggleRow(b);},renderer:function(b,a,c){a.cellAttr='rowspan="2"';
return'<div class="'+this.expanderClass+'">&#160;</div>';},beforeExpand:function(c,a,b){if(this.fireEvent("beforeexpand",this,c,a,b)!==false){if(this.tpl&&this.lazyRender){a.innerHTML=this.getBodyContent(c,b);
}return true;}else{return false;}},toggleRow:function(a){if(typeof a=="number"){a=this.grid.view.getRow(a);
}if(Ext.fly(a).hasClass(this.leafClass)){return;}this[Ext.fly(a).hasClass(this.rowCollapsedClass)?"expandRow":"collapseRow"](a);
},expandRow:function(b){if(typeof b=="number"){b=this.grid.view.getRow(b);}if(Ext.fly(b).hasClass(this.leafClass)){return;
}var c=this.grid.store.getAt(b.rowIndex);var a=Ext.DomQuery.selectNode("tr:nth(2) div.x-grid3-row-body",b);
if(this.beforeExpand(c,a,b.rowIndex)){this.state[c.id]=true;Ext.fly(b).replaceClass(this.rowCollapsedClass,this.rowExpandedClass);
this.fireEvent("expand",this,c,a,b.rowIndex);}},destroyNestedGrids:function(g){if(g){if(childGridEl=g.child(".x-grid-panel")){this.destroyNestedGrids(childGridEl);
}var a=Ext.getCmp(g.id);if(a&&(a!=this.grid)){if(a instanceof Ext.grid.EditorGridPanel){var f=a.getColumnModel();
for(var b=0,c=f.getColumnCount();b<c;b++){for(var d=0,e=a.getStore().getCount();d<e;d++){if(editor=f.getCellEditor(b,d)){editor.destroy();
}}}f.destroy();}a.destroy();}}},collapseRow:function(b){if(typeof b=="number"){b=this.grid.view.getRow(b);
}if(Ext.fly(b).hasClass(this.leafClass)){return;}var c=this.grid.store.getAt(b.rowIndex);var a=Ext.fly(b).child("tr:nth(1) div.x-grid3-row-body",true);
if(this.fireEvent("beforecollapse",this,c,a,b.rowIndex)!==false){this.destroyNestedGrids(Ext.get(b).child(".x-grid-panel"));
if(c){this.state[c.id]=false;}Ext.fly(b).replaceClass(this.rowExpandedClass,this.rowCollapsedClass);this.fireEvent("collapse",this,c,a,b.rowIndex);
}}});Ext.preg("rowexpander",Ext.grid.RowExpander);Ext.ux.Printer=function(){return{renderers:{},registerRenderer:function(a,b){this.renderers[a]=new (b)();
},getRenderer:function(a){return this.renderers[a];},generateHtml:function(b,d,c){var a=['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">',"<html>","<head>",'<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />',(c?'<link href="'+c+'" rel="stylesheet" type="text/css" media="screen,print" />':""),"<title>"+b+"</title>","</head>","<body>",(d||""),"</body>","</html>"];
return a.join("");},print:function(e,h,d,c){var a=this;var g=this.generateHtml(e,h,c);if(Ext.isObject(d)){for(var j in d){var b;
if(Ext.isString(d[j])||Ext.isNumber(d[j])){b=d[j];}else{b=a.renderCmp(d[j]);}reg=new RegExp("\\{"+j+"\\}","gm");
g=g.replace(reg,b);}}var f=window.open("","_new");f.document.write(g);f.document.close();f.print();},renderCmp:function(c){var e=c.getXTypes().split("/");
for(var b=e.length-1;b>=0;b--){var a=e[b],d=this.getRenderer(a);if(d!=undefined){return d.generateHTML(c);
break;}}return"[component render undefined]";},print1:function(c){var e=c.getXTypes().split("/");for(var b=e.length-1;
b>=0;b--){var a=e[b],d=this.getRenderer(a);if(d!=undefined){d.print(c);break;}}}};}();Ext.override(Ext.Component,{getXTypes:function(){var b=this.constructor;
if(!b.xtypes){var d=[],e=this;while(e){var a=e.constructor.xtype;if(a!=undefined){d.unshift(a);}e=e.constructor.superclass;
}b.xtypeChain=d;b.xtypes=d.join("/");}return b.xtypes;}});Ext.ux.Printer.BaseRenderer=Ext.extend(Object,{print:function(b){var c=b&&b.getXType?String.format("print_{0}_{1}",b.getXType(),b.id):"print";
var a=window.open("",c);a.document.write(this.generateHTML(b));a.document.close();a.print();a.close();
},generateHTML:function(a){return new Ext.XTemplate(this.generateBody(a)).apply(this.prepareData(a));
},generateBody:Ext.emptyFn,prepareData:function(a){return a;},getTitle:function(a){return typeof a.getTitle=="function"?a.getTitle():(a.title||"Printing");
},stylesheetPath:"stylesheets/print.css"});Ext.ux.Printer.ColumnTreeRenderer=Ext.extend(Ext.ux.Printer.BaseRenderer,{generateBody:function(a){var d=this.getColumns(a);
var c=this.headerTpl.apply(d);var b=this.bodyTpl.apply(d);return String.format('<table>{0}<tpl for=".">{1}</tpl></table>',c,b);
},getColumns:function(a){return a.columns;},prepareData:function(a){var b=a.root,g=[],e=this.getColumns(a),d=this.indentPadding;
var c=function(f){if(f.hidden===true||f.isHiddenRoot()===true){return;}var h=Ext.apply({depth:f.getDepth()*d},f.attributes);
Ext.iterate(h,function(j,k){Ext.each(e,function(l){if(l.dataIndex==j){h[j]=l.renderer?l.renderer(k):k;
}},this);});h[this.getColumns(a)[0].dataIndex]=f.attributes.text;g.push(h);};b.cascade(c,this);return g;
},indentPadding:15,headerTpl:new Ext.XTemplate("<tr>",'<tpl for=".">','<th width="{width}">{header}</th>',"</tpl>","</tr>"),bodyTpl:new Ext.XTemplate("<tr>",'<tpl for=".">','<td style="padding-left: {[xindex == 1 ? "\\{depth\\}" : "0"]}px">{{dataIndex}}</td>',"</tpl>","</tr>")});
Ext.ux.Printer.registerRenderer("columntree",Ext.ux.Printer.ColumnTreeRenderer);Ext.ux.Printer.GridPanelRenderer=Ext.extend(Ext.ux.Printer.BaseRenderer,{generateBody:function(d){var c=this.getColumns(d);
var a=this.headerTpl.apply(c);var b=this.bodyTpl.apply(c);return String.format('<table>{0}<tpl for=".">{1}</tpl></table>',a,b);
},prepareData:function(c){var a=this.getColumns(c);var b=[];c.store.data.each(function(d){var e={};Ext.iterate(d.data,function(f,g){Ext.each(a,function(h){if(h.dataIndex==f){e[f]=h.renderer?h.renderer(g,null,d):g;
return false;}},this);});b.push(e);});return b;},getColumns:function(b){var a=[];Ext.each(b.getColumnModel().config,function(c){if(c.hidden!=true){a.push(c);
}},this);return a;},headerTpl:new Ext.XTemplate("<tr>",'<tpl for=".">',"<th>{header}</th>","</tpl>","</tr>"),bodyTpl:new Ext.XTemplate("<tr>",'<tpl for=".">',"<td>{{dataIndex}}</td>","</tpl>","</tr>")});
Ext.ux.Printer.registerRenderer("grid",Ext.ux.Printer.GridPanelRenderer);Ext.ux.Printer.PanelRenderer=Ext.extend(Ext.ux.Printer.BaseRenderer,{generateBody:function(a){return String.format("<div class='x-panel-print'>{0}</div>",a.body.dom.innerHTML);
}});Ext.ux.Printer.registerRenderer("panel",Ext.ux.Printer.PanelRenderer);jQuery.ajaxSettings.contentType="application/x-www-form-urlencoded; charset=utf-8";
WebLight.namespace("Bud","Bud.form","Bud.page","Bud.grid");var host=document.location.host;if(!window.top.fin){window.top.fin={appUI:{houseCodeId:415,glbFscYear:4,glbFscPeriod:40}};
}Bud.getGlobalHouseCodeStore=function(){if(!top.globalHouseCodeStore){top.globalHouseCodeStore=new Bud.data.HouseCodeStore();
top.globalHouseCodeStore.load();}else{if(top.globalHouseCodeStore.getCount()>0){top.globalHouseCodeStore.fireEvent("load",top.globalHouseCodeStore,top.globalHouseCodeStore.getRange());
}}return top.globalHouseCodeStore;};Bud.Context={userId:document.location.host=="localhost"?"RAYMOND-DEV-XP\\Raymond+Liu":"[user]",isTest:document.location.host=="localhost",ytdBusinessDays:261,getStickyHcmHouseCode:function(){var a=window.top.fin.appUI.houseCodeId;
if(!a){return 0;}return a;},getStickyFscYear:function(){var a=window.top.fin.appUI.glbFscYear;if(!a){return 0;
}return a;},getStickyFscPeriod:function(){var a=window.top.fin.appUI.glbFscPeriod;if(!a){return 0;}return a;
},setStickyHouseCode:function(d,e,c,b,a){if(window.top.fin.appUI){window.top.fin.appUI.unitId=d;window.top.fin.appUI.houseCodeId=parseFloat(e);
window.top.fin.appUI.houseCodeTitle=c;window.top.fin.appUI.houseCodeBrief=b;window.top.fin.appUI.hirNode=a;
}},setStickyFiscalYear:function(b,a){if(window.top.fin.appUI){window.top.fin.appUI.glbFscYear=parseFloat(b);
window.top.fin.appUI.glbfiscalYear=a;}},setStickyFiscalPeriod:function(b,a){if(window.top.fin.appUI){window.top.fin.appUI.glbFscPeriod=parseFloat(b);
window.top.fin.appUI.glbPeriod=a;}}};Ext.override(Ext.form.Field,{showItem:function(){if(!Ext.isEmpty(this.getEl())){this.getEl().up(".x-form-item").setDisplayed(true);
}},hideItem:function(){if(!Ext.isEmpty(this.getEl())){this.getEl().up(".x-form-item").setDisplayed(false);
}}});Ext.override(Ext.form.DisplayField,{setRawValue:function(a){if(this.htmlEncode){a=Ext.util.Format.htmlEncode(a);
}if(this.dateFormat&&Ext.isDate(a)){a=a.dateFormat(this.dateFormat);}if(this.numberFormat){if(a==0||a==""){if(this.numberFormat.indexOf(",")>0){a=this.numberFormat.substring(4);
}else{a=this.numberFormat;}}else{if(typeof a=="number"){a=Ext.util.Format.number(a,this.numberFormat);
}}}if(this.rendered){if(Ext.isEmpty(a)){this.el.dom.innerHTML="";}else{this.el.dom.innerHTML=a;}}else{this.value=a;
}}});Ext.override(Ext.form.NumberField,{allowBlank:false});Bud.form.DropdownList=Ext.extend(Ext.form.ComboBox,{mode:"local",forceSelection:true,triggerAction:"all",selectOnFocus:true,editable:false,layzeInit:false,typeAhead:true,allowBlank:false,initComponent:function(){Bud.form.DropdownList.superclass.initComponent.call(this);
},setValue:function(b){var a=this.value;this.innerValue=b;Bud.form.DropdownList.superclass.setValue.call(this,b);
if(a!=b){this.fireEvent("valuechange",b,this.getRawValue());}return this;}});Bud.grid.GridPanel=Ext.extend(WebLight.grid.GridPanel,{constructor:function(a){if(a&&a.width){if(a.width>$(window).width()-35){a.width=$(window).width()-35;
}}Bud.grid.GridPanel.superclass.constructor.call(this,a);}});Bud.grid.EditorGridPanel=Ext.extend(Ext.grid.EditorGridPanel,{lastSelectedCell:null,constructor:function(a){if(a&&a.width){if(a.width>$(window).width()-35){a.width=$(window).width()-35;
}}Bud.grid.EditorGridPanel.superclass.constructor.call(this,a);},initComponent:function(){Bud.grid.EditorGridPanel.superclass.initComponent.call(this);
var a=this;this.getView().on("beforerefresh",function(b){a.lastSelectedCell=a.getSelectionModel().getSelectedCell();
});a.on("render",function(){a.getStore().on("beforeload",function(){a.getSelectionModel().clearSelections();
});a.resizeHeaderDiv();a.getView().on("refresh",function(){a.resizeHeaderDiv();});});setTimeout(function(){a.getView().on("refresh",function(b){if(a.lastSelectedCell){a.getSelectionModel().select(a.lastSelectedCell[0],a.lastSelectedCell[1]);
a.startEditing(a.lastSelectedCell[0],a.lastSelectedCell[1]);a.lastSelectedCell=null;}});},100);},resizeHeaderDiv:function(){var b=$("#"+this.id).width();
var a=$(".x-grid3-header-offset",$("#"+this.id)).width();if(a<b){a=b-25;}$(".x-grid3-header",$("#"+this.id)).width(a);
},startEditing:function(f,j){var h=this;if(h.lastSelectedCell&&f==h.lastSelectedCell[0]&&j==h.lastSelectedCell[1]){return;
}this.stopEditing();if(this.colModel.isCellEditable(j,f)){this.view.ensureVisible(f,j,true);var b=this.store.getAt(f),g=this.colModel.getDataIndex(j),a={grid:this,record:b,field:g,value:b.data[g],row:f,column:j,cancel:false};
if(this.fireEvent("beforeedit",a)!==false&&!a.cancel){this.editing=true;var c=this.colModel.getCellEditor(j,f);
if(!c){return;}if(!c.rendered){c.parentEl=this.view.getEditorParent(c);c.on({scope:this,render:{fn:function(e){e.field.focus(false,true);
},single:true,scope:this},specialkey:function(l,k){this.getSelectionModel().onEditorKey(l,k);},complete:this.onEditComplete,canceledit:this.stopEditing.createDelegate(this,[true])});
}Ext.apply(c,{row:f,col:j,record:b});this.lastEdit={row:f,col:j};this.activeEditor=c;c.selectSameEditor=(this.activeEditor==this.lastActiveEditor);
var d=this.preEditValue(b,g);c.startEdit(this.view.getCell(f,j).firstChild,Ext.isDefined(d)?d:"");c.field.focus(true,true);
(function(){if(c.noNeedDeleteselectSameEditor!==true){delete c.selectSameEditor;}}).defer(50);}}}});function GetCursorLocation(a){var b,c,e,d=-1;
if(typeof a.selectionStart=="number"){d=a.selectionStart;}else{if(document.selection&&a.createTextRange){b=document.selection;
if(b){e=b.createRange();c=a.createTextRange();c.setEndPoint("EndToStart",e);d=c.text.length;}}}return d;
}Ext.override(Ext.grid.CellSelectionModel,{handleKeyDown:function(a){var t=this.grid,b=this.selection;
if(!b){a.stopEvent();var u=t.walkCells(0,0,1,this.isSelectable,this);if(u){this.select(u[0],u[1]);}return;
}var m=this;var f=function(g,e,c){return t.walkCells(g,e,c,m.isSelectable,m);};var h=a.getKey(),d=b.cell[0],o=b.cell[1];
var n;if(!a.isNavKeyPress()&&!a.isSpecialKey()){var p=h;var q=String.fromCharCode(p).toLowerCase();var j=t.getStore().getAt(d);
var l=t.colModel.getDataIndex(o);if(a.shiftKey){q=q.toUpperCase();}t.startEditing(d,o);j.data[l]=q;}else{switch(h){case a.TAB:if(a.shiftKey){n=f(d,o-1,-1);
}else{n=f(d,o+1,1);}break;case a.DOWN:n=f(d+1,o,1);break;case a.UP:n=f(d-1,o,-1);break;case a.RIGHT:n=f(d,o+1,1);
break;case a.LEFT:n=f(d,o-1,-1);break;case a.ENTER:if(t.isEditor&&!t.editing){t.startEditing(d,o);a.stopEvent();
t.getView().focusCell(d,o);return;}break;}}if(n){this.select(n[0],n[1]);a.stopEvent();}},onEditorKey:function(f,b){var c=null;
var j=b.getKey(),c,a=this.grid,h=a.activeEditor;if(j==b.TAB){if(b.shiftKey){c=a.walkCells(h.row,h.col-1,-1,this.acceptsNav,this);
}else{c=a.walkCells(h.row,h.col+1,1,this.acceptsNav,this);}b.stopEvent();}else{if(j==b.ENTER){h.completeEdit();
b.stopEvent();}else{if(j==b.ESC){b.stopEvent();h.cancelEdit();a.getView().focusCell(h.row,h.col);}else{if(j==b.DOWN){h.completeEdit();
b.stopEvent();c=a.walkCells(h.row+1,h.col,1,this.acceptsNav,this);h.noNeedDeleteselectSameEditor=true;
h.field.focus(true,true);}else{if(j==b.UP){h.completeEdit();b.stopEvent();c=a.walkCells(h.row-1,h.col,-1,this.acceptsNav,this);
h.noNeedDeleteselectSameEditor=true;h.field.focus(true,true);}else{if(j==b.LEFT){}}}}}}var d=this;if(c){a.startEditing(c[0],c[1]);
setTimeout(function(){h.field.focus(true,true);},100);}}});function getDaysInMonth(b,a){return new Date(b,a,0).getDate();
}if(!window.console){window.console={log:function(){}};}function calcDaysInDateRange(b,a){b.setHours(0,0,0,0);
a.setHours(0,0,0,0);return Math.round((a.getTime()-b.getTime())/(1000*60*60*24))+1;}function calcBusinessDays(d,b){d.setHours(0,0,0,0);
b.setHours(0,0,0,0);var e=d.getDay();var f=b.getDay();var c=Math.round((b.getTime()-d.getTime())/(1000*60*60*24))+(e==6?-1:e)+(f==0?0:7-f);
var a=c/7;var g=a*5-(e<=5&&e>=1?e-1:0)-(f<=5&&f>0?5-f:0);return g;}WebLight.Router.mapRoute("^budget/startbudget$",{xtype:"startbudget"});
WebLight.Router.mapRoute("^budget/contractbilling$",{xtype:"contractbilling"});WebLight.Router.mapRoute("^budget/staffing$",{xtype:"staffing"});
WebLight.Router.mapRoute("^budget/employee$",{xtype:"employee"});WebLight.Router.mapRoute("^budget/mgthist$",{xtype:"managementhistory"});
WebLight.Router.mapRoute("^budget/laborcalculate$",{xtype:"laborcalculations"});WebLight.Router.mapRoute("^budget/fnllaborcalc$",{xtype:"finallaborcalculations"});
WebLight.Router.mapRoute("^budget/supplyexp$",{xtype:"supplyexpenditures"});WebLight.Router.mapRoute("^budget/capitalexp$",{xtype:"capitalexpenditures"});
WebLight.Router.mapRoute("^budget/bgtadj$",{xtype:"budgetadjustments"});WebLight.Router.mapRoute("^budget/bgtdetails$",{xtype:"budgetdetails"});
WebLight.Router.mapRoute("^budget/bgtsummary$",{xtype:"budgetsummary"});WebLight.Router.mapRoute("^budget/bgtapproval$",{xtype:"budgetapproval"});
WebLight.Router.mapRoute("^projection/annualprojectionsbyperiod$",{xtype:"annualprojectionsbyperiod",cacheable:true});
WebLight.Router.mapRoute("^projection/worforecast$",{xtype:"worforecast",cacheable:true});WebLight.Router.mapRoute("^budSummary/summary$",{xtype:"budgetsummary"});
WebLight.Router.mapRoute("^ledger/transactionsummary$",{xtype:"transactionsummary"});WebLight.Router.mapRoute("^epaySchedule/uploadsites$",{xtype:"epaySchedule_uploadsites"});
WebLight.Router.mapRoute("^epaySchedule/epaytaskcallhistory$",{xtype:"epaytaskcallhistory"});WebLight.Router.mapRoute("^epaySchedule/uploademployees$",{xtype:"epaySchedule_uploademployees"});
WebLight.Router.mapRoute("^epaySchedule/downloadhours$",{xtype:"epaySchedule_downloadhours"});Bud.NavbarItem=Ext.extend(Ext.Button,{url:null,initComponent:function(){Bud.NavbarItem.superclass.initComponent.call(this);
if(!this.handler&&this.url){this.setHandler(function(){WebLight.Router.route(this.url);},this);}}});Bud.TransactionSummaryNavBar=Ext.extend(Ext.Toolbar,{initComponent:function(){var a=[];
a.push(new Bud.NavbarItem({text:"Transaction Summary",pattern:"ledger/transactionsummary",url:"/ledger/transactionsummary"}));
this.items=a;this.menuItems=a;Bud.TransactionSummaryNavBar.superclass.initComponent.call(this);var b=function(c){Ext.each(a,function(e){if(e.pattern){var d=new RegExp(e.pattern,"gi");
d.test(c)?e.addClass("x-btn-active"):e.removeClass("x-btn-active");}});};WebLight.PageMgr.on("load",function(c,d){b(c);
});WebLight.PageMgr.on("resume",function(c,d){b(c);});}});WebLight.namespace("Bud.data");Bud.data.XmlReader=WebLight.extend(Ext.data.XmlReader,{dataLoaded:false,read:function(c){var a=this;
a.dataLoaded=true;var b=c.responseText;if(b.indexOf("transmission Error")>0){a.dataLoaded=false;}var d=c.responseXML;
if(!d){throw {message:"XmlReader.read: XML Document not available"};}return this.readRecords(d);}});Bud.data.XmlStore=WebLight.extend(WebLight.data.Store,{url:"/net/crothall/chimes/fin/bud/act/Provider.aspx",recordName:"item",isAnnualizedStore:true,constructor:function(a){var b=this;
a=a||{};var e=a.fields||this.fields;var d=a.reader||this.reader;var c=a.idProperty||this.idProperty;if(!c){c="@id";
}if(!d&&e&&e.length){d=new Bud.data.XmlReader({record:b.recordName,idProperty:c},e);a.reader=d;this.reader=d;
}Bud.data.XmlStore.superclass.constructor.call(this,a);},isDataLoaded:function(){return this.reader.dataLoaded;
},requestId:2,moduleId:"bud",targetId:"iiCache",storeId:"",getRequestId:function(){var a=this;switch(a.storeId){case"hcmHouseCodes":return 3;
case"houseCodes":return 4;case"budAnnualBudgets":return 5;case"budAnnualInformations":return 6;case"houseCodeJobs":return 7;
case"fiscalYears":return 8;}return 2;},getStoreId:function(){return this.storeId;},getCriteria:function(){return{};
},getRequestXml:function(){var d=["<criteria>"];var b=this.getCriteria();var a="[user]";var c=document.location.host;
if(c=="localhost"||c.substr(0,10)=="persistech"){a="RAYMOND-DEV-XP\\Raymond Liu";}b=Ext.apply(b||{},{storeId:this.getStoreId(),userId:a});
for(i in b){d.push(String.format("{0}:{1},",i,b[i]));}d.push("</criteria>");return d.join("");},load:function(a){this.setBaseParam("requestId",this.getRequestId());
this.setBaseParam("moduleId",this.moduleId);this.setBaseParam("targetId",this.targetId);this.setBaseParam("requestXml",this.getRequestXml());
Bud.data.XmlStore.superclass.load.call(this,{});},reload:function(a){this.setBaseParam("requestId",this.getRequestId());
this.setBaseParam("moduleId",this.moduleId);this.setBaseParam("targetId",this.targetId);this.setBaseParam("requestXml",this.getRequestXml());
Bud.data.XmlStore.superclass.load.call(this,{});},loadData:function(a){var b;if(window.ActiveXObject){b=new ActiveXObject("Microsoft.XMLDOM");
b.async="false";b.loadXML(a);}else{b=new DOMParser().parseFromString(a,"text/xml");}Bud.data.XmlStore.superclass.loadData.call(this,b);
},addAttributes:function(a){},_ignoredRecords:null,ignoreRecords:function(a){var b=this;if(null==b._ignoredRecords){b._ignoredRecords=[];
}if(WebLight.isArray(a)){b._ignoredRecords.concat(a);}else{b._ignoredRecords.push(a);}},getChangedRecords:function(){var b=this;
var a=Bud.data.XmlStore.superclass.getChangedRecords.call(this);if(null==b._ignoredRecords){return a;
}var c=[];WebLight.each(a,function(d){if(b._ignoredRecords.indexOf(d)==-1){c.push(d);}});return c;},submitChanges:function(c){var e=this;
this.fireEvent("beforesubmit",this);var a=['<transaction id="1">'];var f=0;var g=0;var b=0;var h=function(j){return String(j).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/'/g,"&#39;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
};Ext.each(this.getChangedRecords(),function(k,l){a.push("<");a.push(e.getStoreId().replace(/s$/,""));
e.addAttributes(k.data);for(key in k.data){var j=k.data[key];if(Ext.isDate(j)){j=Ext.util.Format.date(j,"m/d/Y");
}else{if(Ext.isString(j)){j=h(j);}}a.push(String.format(' {0}="{1}"',key,j));if(key=="hcmHouseCode"){f=parseFloat(j);
}else{if(key=="hcmJob"){g=parseFloat(j);}else{if(key=="fscYear"){b=parseFloat(j);}}}}a.push("/>");},this);
a.push("</transaction>");var d=String.format("moduleId={0}&requestId={1}&requestXml={2}&&targetId=iiTransaction",this.moduleId,this.requestId,encodeURIComponent(a.join("").replace(/\&/gi,"&amp;")));
jQuery.post(this.url,d,function(l,j){var k=function(){if(c){c(l,j);}e.fireEvent("submit");e.changes=[];
};if(e.isAnnualizedStore){e.updateBudDetails(f,g,b,k);}else{k();}});},updateBudDetails:function(f,c,e,a){var d='<transaction id="1"><budDetailUpdate hcmHouseCode="'+f+'" hcmJob="'+c+'" fscYear="'+e+'"/></transaction>';
var b=String.format("moduleId={0}&requestId={1}&requestXml={2}&&targetId=iiTransaction",this.moduleId,this.requestId,encodeURIComponent(d));
jQuery.post(this.url,b,function(h,g){if(a){a(h,g);}a();});}});Bud.data.XmlStore._requestId=2;Bud.data.AuthorizationStore=WebLight.extend(Bud.data.XmlStore,{url:"/net/crothall/chimes/fin/bud/act/Provider.aspx",moduleId:"bud",targetId:"iiAuthorization",recordName:"authorize",fields:[{name:"id",mapping:"@id"},{name:"path",mapping:"@path"}],getRequestXml:function(){return'<authorization id="1"><authorize path="\\crothall\\chimes\\fin\\Budgeting"/></authorization>';
},loadSampleData:function(){this.loadData(_builtInTemplate_a3bcf709[0]);},allowBudgetRead:function(){return this.authorized("\\crothall\\chimes\\fin\\Budgeting\\AnnualizedBudget\\Read");
},allowBudgetWrite:function(){return this.authorized("\\crothall\\chimes\\fin\\Budgeting\\AnnualizedBudget\\Write");
},allowWORRead:function(){return this.authorized("\\crothall\\chimes\\fin\\Budgeting\\AnnualProjections\\WORForecast\\Read");
},allowWORWrite:function(){return this.authorized("\\crothall\\chimes\\fin\\Budgeting\\AnnualProjections\\WORForecast\\Write");
},allowAnnualProjectionRead:function(){return this.authorized("\\crothall\\chimes\\fin\\Budgeting\\AnnualProjections\\ByPeriod\\Read");
},allowAnnualProjectionWrite:function(){return this.authorized("\\crothall\\chimes\\fin\\Budgeting\\AnnualProjections\\ByPeriod\\Write");
},allowBudgetSummaryRead:function(){return this.authorized("\\crothall\\chimes\\fin\\Budgeting\\BudgetSummary\\Read");
},allowBudgetSummaryWrite:function(){return this.authorized("\\crothall\\chimes\\fin\\Budgeting\\BudgetSummary\\Write");
},allowApproveBudget:function(){return this.authorized("\\crothall\\chimes\\fin\\Budgeting\\AnnualizedBudget\\ApproveBudget\\Approve");
},allowRejectBudget:function(){return this.authorized("\\crothall\\chimes\\fin\\Budgeting\\AnnualizedBudget\\ApproveBudget\\Reject");
},authorized:function(a){if(Bud.Context.isTest){return true;}return this.queryBy(function(b){return b.get("path")==a;
}).getCount()>0;},idAuthorized:function(a){return this.queryBy(function(b){return b.get("id")==a;}).getCount()>0;
}});WebLight.namespace("Bud.data");Bud.data.FiscalYearStore=WebLight.extend(Bud.data.XmlStore,{url:"/net/crothall/chimes/fin/app/act/Provider.aspx",moduleId:"fsc",storeId:"fiscalYears",fields:[{name:"id",mapping:"@id"},{name:"title",mapping:"@title"}],minFscYear:1,constructor:function(a){Bud.data.FiscalYearStore.superclass.constructor.call(this,a);
var b=this;this.on("load",function(){this.each(function(c){if(c.get("id")<b.minFscYear){b.remove(c);}});
});}});Bud.data.FiscalPeriodStore=WebLight.extend(Bud.data.XmlStore,{url:"/net/crothall/chimes/fin/app/act/Provider.aspx",moduleId:"fsc",fiscalYearId:0,storeId:"fiscalPeriods",constructor:function(a){Bud.data.FiscalPeriodStore.superclass.constructor.call(this,a);
this.on({add:{fn:this.updateTotals},remove:{fn:this.updateTotals},update:{fn:this.updateTotals},datachanged:{fn:this.updateTotals}});
this.on("load",function(){Bud.Context.ytdBusinessDays=this.getTotalBusinessDays();});},updateTotals:function(){this.suspendEvents(false);
for(var b=0;b<this.getCount();b++){var c=this.getAt(b);var d=Ext.util.Format.date(c.get("startDate"),"m/d/Y");
var a=Ext.util.Format.date(c.get("endDate"),"m/d/Y");c.set("friendlyTitle",String.format("{0}: {1} - {2}",c.get("title"),d,a));
}this.resumeEvents();},getCriteria:function(){return{fiscalYearId:this.fiscalYearId};},fields:[{name:"id",mapping:"@id"},{name:"fiscalYearId",mapping:"@year"},{name:"title",mapping:"@title"},{name:"fiscalYear",mapping:"@fscYeaTitle"},{name:"startDate",mapping:"@startDate",type:"date",dateFormat:"n/j/Y"},{name:"endDate",mapping:"@endDate",type:"date",dateFormat:"n/j/Y"},{name:"friendlyTitle"}],load:function(a){this.fiscalYearId=a;
Bud.data.FiscalPeriodStore.superclass.load.call(this);},getByTitle:function(c){var b=this;var a=b.findBy(function(d,e){return d.get("title")==c;
});return b.getAt(a);},getBusinessDaysByTitle:function(b){var a=this;var c=a.getByTitle(b);return calcBusinessDays(c.get("startDate"),c.get("endDate"));
},getDaysByTitle:function(b){var a=this;var c=a.getByTitle(b);return calcDaysInDateRange(c.get("startDate"),c.get("endDate"));
},getTotalBusinessDays:function(){var a=this;var c=a.getByTitle(1);var b=a.getByTitle(12);return calcBusinessDays(c.get("startDate"),b.get("endDate"));
}});WebLight.namespace("Bud.data");Bud.data.HouseCodeReader=WebLight.extend(Ext.data.XmlReader,{read:function(a){top.bud_housecodexml=a.responseText;
var b=a.responseXML;if(!b){throw {message:"XmlReader.read: XML Document not available"};}return this.readRecords(b);
}});Bud.data.HouseCodeStore=WebLight.extend(Bud.data.XmlStore,{url:"/net/crothall/chimes/fin/hcm/act/provider.aspx",moduleId:"hcm",storeId:"hcmHouseCodes",getCriteria:function(){var a=this;
return{appUnitBrief:a.baseParams.query||""};},fields:[{name:"id",mapping:"@id"},{name:"name",mapping:"@name"},{name:"number",mapping:"@number"},{name:"brief",mapping:"@brief"},{name:"appUnit",mapping:"@appUnit"},{name:"hirNode",mapping:"@hirNode"}],constructor:function(a){a=a||{};
var b=new Bud.data.HouseCodeReader({record:"item",idProperty:"@id"},this.fields);a.reader=b;Bud.data.HouseCodeStore.superclass.constructor.call(this,a);
},load:function(a){if(top.bud_housecodexml){this.loadData(top.bud_housecodexml);}else{this.setBaseParam("requestId",this.getRequestId());
this.setBaseParam("moduleId",this.moduleId);this.setBaseParam("targetId",this.targetId);this.setBaseParam("requestXml",this.getRequestXml());
Bud.data.XmlStore.superclass.load.call(this,{});}}});WebLight.namespace("Bud.data");Bud.data.JobCodeStore=WebLight.extend(Bud.data.XmlStore,{url:"/net/crothall/chimes/fin/hcm/act/Provider.aspx",moduleId:"hcm",idProperty:"@jobId",fields:[{name:"id",mapping:"@id"},{name:"jobTitle",mapping:"@jobTitle"},{name:"jobDescription",mapping:"@jobDescription"},{name:"jobNumber",mapping:"@jobNumber"},{name:"houseCodeId",mapping:"@houseCodeId"},{name:"jobId",mapping:"@jobId"}],storeId:"houseCodeJobs",getCriteria:function(){return{houseCodeId:this.houseCodeId,jobType:0};
},load:function(a){this.houseCodeId=a;Bud.data.JobCodeStore.superclass.load.call(this);}});WebLight.namespace("Bud.data");
Bud.data.BudgetAccountStore=WebLight.extend(Bud.data.XmlStore,{url:"/net/crothall/chimes/fin/bud/act/Provider.aspx",moduleId:"bud",storeId:"budFscAccounts",wor:"",fields:[{name:"id",mapping:"@id",type:"float"},{name:"accountCategoryId",mapping:"@accountCategoryId",type:"float"},{name:"accountCategory",mapping:"@accountCategory"},{name:"code",mapping:"@code"},{name:"glHeader",mapping:"@glHeader"},{name:"isNegative",mapping:"@isNegative",type:"bool"},{name:"name",mapping:"@name"},{name:"categoryDisplayOrder",mapping:"@categoryDisplayOrder",type:"float"},{name:"displayOrder",mapping:"@displayOrder",type:"float"},{name:"friendlyName"}],constructor:function(a){Bud.data.BudgetAccountStore.superclass.constructor.call(this,a);
this.on({add:{fn:this.updateTotals},remove:{fn:this.updateTotals},update:{fn:this.updateTotals},datachanged:{fn:this.updateTotals}});
},load:function(a){if(a){this.wor=a;}Bud.data.BudgetAccountStore.superclass.load.call(this);},getCriteria:function(){return{budget:1,wor:this.wor};
},updateTotals:function(){this.suspendEvents(false);this.each(function(b){var a=b.get("code");var c=b.get("name");
b.set("friendlyName",String.format("{0} - {1}",a,c));});this.resumeEvents();}});WebLight.namespace("Bud.data");
Bud.data.BudDetailsStore=WebLight.extend(Bud.data.XmlStore,{url:"/net/crothall/chimes/fin/bud/act/Provider.aspx",moduleId:"bud",storeId:"budDetails",_hcmHouseCode:0,_fscYear:0,_hcmJob:0,_accountStore:null,isInitialed:false,fields:[{name:"id",mapping:"@id",type:"float"},{name:"hcmHouseCode",mapping:"@hcmHouseCode",type:"float"},{name:"hcmJob",mapping:"@hcmJob",type:"float"},{name:"fscYear",mapping:"@fscYear",type:"float"},{name:"fscAccount",mapping:"@fscAccount",type:"float"},{name:"amount",mapping:"@amount",type:"float"},{name:"entAt",mapping:"@entAt",type:"date"},{name:"entBy",mapping:"@entBy",type:"string"},{name:"isReadOnly",mapping:"@isReadOnly",type:"bool"},{name:"period0",mapping:"@period0",type:"float"},{name:"period1",mapping:"@period1",type:"float"},{name:"period2",mapping:"@period2",type:"float"},{name:"period3",mapping:"@period3",type:"float"},{name:"period4",mapping:"@period4",type:"float"},{name:"period5",mapping:"@period5",type:"float"},{name:"period6",mapping:"@period6",type:"float"},{name:"period7",mapping:"@period7",type:"float"},{name:"period8",mapping:"@period8",type:"float"},{name:"period9",mapping:"@period9",type:"float"},{name:"period10",mapping:"@period10",type:"float"},{name:"period11",mapping:"@period11",type:"float"},{name:"period12",mapping:"@period12",type:"float"},{name:"period13",mapping:"@period13",type:"float"},{name:"period14",mapping:"@period14",type:"float"},{name:"period15",mapping:"@period15",type:"float"},{name:"period16",mapping:"@period16",type:"float"},{name:"total",type:"float"},{name:"fscAccCode"},{name:"description"},{name:"accountCategoryId",type:"float"},{name:"accountCategory"},{name:"percentage",type:"float"},{name:"isNegative"}],constructor:function(a){Bud.data.BudDetailsStore.superclass.constructor.call(this,a);
this.on({add:{fn:this.updateTotals},remove:{fn:this.updateTotals},update:{fn:this.updateTotals}});},getCriteria:function(){return{hcmHouseCode:this._hcmHouseCode,fscYear:this._fscYear,hcmJob:this._hcmJob};
},addAttributes:function(a){Ext.apply(a,{hcmHouseCode:this._hcmHouseCode,hcmJob:this._hcmJob,fscYear:this._fscYear});
},round2:function(a){return Math.round(a*100)/100;},calculate:function(b,a){if(a){return b/a;}if(b){return 1;
}return 0;},calculating:true,updateTotals:function(){var b=this;b.currentUpdatingTick++;var a=b.currentUpdatingTick;
setTimeout(function(){b.innerUpdateTotals(a);},2000);},currentUpdatingTick:0,innerUpdateTotals:function(h){var g=this;
if(h!=g.currentUpdatingTick){return;}if(g.calculating){return;}this.suspendEvents(false);g.calculating=true;
if(this.isInitialed){var c=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];this.each(function(m){if(!m.get("fscAccCode")){var l=m.get("id");
var j=g.queryBy(function(p,q){return p.get("accountCategoryId")==l;});var o=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];
j.each(function(t,u){var s=t.get("isNegative");for(var q=0;q<16;q++){var r="period"+(q+1);var p=t.get(r);
o[q]+=s?-p:p;if(t.get("accountCategoryId")){c[q]+=s?-p:p;}}});for(var k=0;k<16;k++){var n="period"+(k+1);
if(m.get(n)!=g.round2(o[k])){m.set(n,g.round2(o[k]));}}}});var e=this.getAt(this.getCount()-1);for(var d=0;
d<16;d++){var b="period"+(d+1);e.set(b,g.round2(-c[d]));}this.each(function(l){var k=0;for(var j=0;j<12;
j++){var m="period"+(j+1);k+=l.get(m);}if(l.get("total")!=g.round2(k)){l.set("total",g.round2(k));}});
var a=this.queryBy(function(j,k){return j.get("id")==45&&j.get("accountCategoryId")==0;});if(a&&a.getCount()==1){var f=a.get(0).get("total");
g.each(function(j){var k=g.calculate(j.get("total"),f);if(k!=j.get("percentage")){j.set("percentage",k);
}});}}g.calculating=false;this.resumeEvents();if(g.firstCalculating===true){g.commitChanges();g.firstCalculating=false;
}this.resumeEvents();this.fireEvent("datarefresh",this);},getChangedRecords:function(){var a=[];var b=Bud.data.BudDetailsStore.superclass.getChangedRecords.call(this);
Ext.each(b,function(c,d){if(c.get("fscAccount")&&(c.get("_sysStatus")==1||c.get("_sysStatus")==2)){a.push(c);
}});return a;},load:function(c,a,b){this._fscYear=b;this._hcmHouseCode=c;this._hcmJob=a;Bud.data.BudDetailsStore.superclass.load.call(this);
},reload:function(){var a=this;a.isInitialed=false;Bud.data.BudDetailsStore.superclass.reload.call(this);
},assign:function(a){if(this.getCount()>0){this.each(function(c){var b=a.getById(c.get("fscAccount"));
if(b){c.set("fscAccCode",b.get("code"));c.set("description",b.get("name"));c.set("accountCategoryId",b.get("accountCategoryId"));
c.set("accountCategory",b.get("accountCategory"));c.set("isNegative",b.get("isNegative"));}});this.sort("fscAccCode","ASC");
}},relateTo:function(b){var h=this;this._accountStore=b;var f={};for(var g=0;g<16;g++){var c=String.format("period{0}",g+1);
f[c]=0;}if(this.getCount()==0){this.add(h.newRecord(Ext.apply({id:0,description:"Total"},f)));return;
}h.calculating=true;h.assign(b);for(var g=0;g<this.getCount();g++){var j=this.getAt(g);var a=j.get("accountCategoryId");
var k=j.get("accountCategory");var d=h.queryBy(function(l,m){return l.get("accountCategoryId")==a;});
var e=d.getCount();h.insert(g+e,h.newRecord(Ext.apply({id:a,description:k,accountCategoryId:0},f)));g+=e;
}this.add(h.newRecord(Ext.apply({id:0,description:"Total"},f)));h.calculating=false;this.isInitialed=true;
h.firstCalculating=true;h.updateTotals();},addNewRecord:function(m){var k=this;k.calculating=true;var b=m.get("code");
var a=m.get("accountCategoryId");var n=m.get("accountCategory");var l=k.queryBy(function(c){return c.get("fscAccCode")==b;
});if(l.getCount()>0){alert("Account already exists.");return;}var g={};for(var h=0;h<16;h++){var e=String.format("period{0}",h+1);
g[e]=0;}var j=function(c){k.insert(c,k.newRecord(Ext.apply({description:m.get("name"),fscAccCode:b,fscAccount:m.get("id"),accountCategoryId:a,accountCategory:n,isReadOnly:0,isNegative:m.get("isNegative")},g)));
};var d=k.queryBy(function(c,o){return c.get("accountCategoryId")==a;});var f=k.findBy(function(c){return !c.get("fscAccCode")&&c.get("id")==a&&c.get("accountCategoryId")==0;
});if(f<0){j(0);k.insert(1,k.newRecord(Ext.apply({id:a,description:n,accountCategoryId:0},g)));}else{j(f);
}k.isInitialed=true;k.calculating=false;k.updateTotals();}});Bud.data.AppJDEGLTransactionStore=WebLight.extend(Bud.data.XmlStore,{url:"/net/crothall/chimes/fin/glm/act/Provider.aspx",moduleId:"glm",storeId:"appJDEGLTransaction2",_hcmHouseCode:0,_hcmJob:0,_fscYear:0,_fscPeriod:0,_direction:0,getCriteria:function(){return{hcmHouseCode:this._hcmHouseCode,hcmJob:this._hcmJob,fscYear:this._fscYear,fscPeriod:this._fscPeriod,direction:this._direction};
},load:function(e,c,d,a,b){this._hcmHouseCode=e;this._fscYear=d;this._fscPeriod=a;this._hcmJob=c;this._direction=b;
Bud.data.AppJDEGLTransactionStore.superclass.load.call(this);},fields:[{name:"id",mapping:"@id",type:"int"},{name:"hcmHouseCode",mapping:"@hcmHouseCode",type:"int"},{name:"hcmJob",mapping:"@hcmJob",type:"int"},{name:"fscYear",mapping:"@fscYear",type:"int"},{name:"fscPeriod",mapping:"@fscPeriod",type:"int"},{name:"fscAccount",mapping:"@fscAccount",type:"int"},{name:"vendor",mapping:"@vendor",type:"string"},{name:"week1",mapping:"@week1",type:"float"},{name:"week2",mapping:"@week2",type:"float"},{name:"week3",mapping:"@week3",type:"float"},{name:"week4",mapping:"@week4",type:"float"},{name:"total",mapping:"@total",type:"float"}]});
Bud.data.TransactionSummaryStore=WebLight.extend(Bud.data.XmlStore,{hcmHouseCode:-1,hcmJob:-1,fscYear:-1,fscPeriod:-1,isAnnualizedStore:false,_periodTitle:0,_addingTotalRow:false,_loading:false,_loadedStoreCount:0,_totalRow:null,fscYearStore:null,fscPeriodStore:null,fscPeriodCount:13,fscAccountStore:null,budDetailStore:null,appJDEGLTransactionStore:null,previousAppJDEGLTransactionStore:null,projectionStore:null,nextProjectionStore:null,constructor:function(a){var b=this;
var c=[{name:"fscAccount",type:"float"},{name:"title"},{name:"accCode"},{name:"isNegative",type:"bool"},{name:"accountCategoryId",type:"float"},{name:"accountCategory"},{name:"vendor"},{name:"week1",mapping:"@week1",type:"float"},{name:"week2",mapping:"@week2",type:"float"},{name:"week3",mapping:"@week3",type:"float"},{name:"week4",mapping:"@week4",type:"float"},{name:"total",type:"float"},{name:"budget",type:"float"},{name:"variance",type:"float"},{name:"actual",type:"float"},{name:"periodProjection1",type:"float"},{name:"periodProjection2",type:"float"},{name:"subStore",type:"auto"},{name:"noChildren",type:"bool"}];
a=Ext.apply(a||{},{record:"item",idProperty:"@fscAccount",fields:c});Bud.data.TransactionSummaryStore.superclass.constructor.call(this,a);
b.on({add:{fn:this.calculateStore},remove:{fn:this.calculateStore},update:{fn:this.calculateStore}});
b.budDetailStore=new Bud.data.BudDetailsStore();b.appJDEGLTransactionStore=new Bud.data.AppJDEGLTransactionStore();
b.previousAppJDEGLTransactionStore=new Bud.data.AppJDEGLTransactionStore();b.projectionStore=new Bud.data.BudProjectedDetailStore();
b.nextProjectionStore=new Bud.data.BudProjectedDetailStore();b.budDetailStore.on("load",b.subStoreLoaded.createDelegate(this));
b.appJDEGLTransactionStore.on("load",b.subStoreLoaded.createDelegate(this));b.previousAppJDEGLTransactionStore.on("load",b.subStoreLoaded.createDelegate(this));
b.projectionStore.on("load",b.subStoreLoaded.createDelegate(this));b.nextProjectionStore.on("load",b.subStoreLoaded.createDelegate(this));
},clearStore:function(){var a=this;a.suspendEvents(false);a.remove(a.getRange());a.resumeEvents();},subStoreLoaded:function(){var b=this;
b._loadedStoreCount+=1;var a=parseInt(b._periodTitle);if(a<b.fscPeriodCount&&b._loadedStoreCount==4||a==b.fscPeriodCount&&b._loadedStoreCount==5){b._loading=false;
b.clearStore();b.suspendEvents(false);b.populateStore();b._addingTotalRow=true;b.add(b._totalRow);b.ignoreRecords(b._totalRow);
b._addingTotalRow=false;b.calculateStore();b.resumeEvents();b.fireEvent("load",b);}},getByFscAccount:function(a){var d=this;
var b=d.queryBy(function(h){return h.get("fscAccount")==a;});var g=b.get(0);if(!g){var f=d.fscAccountStore.getById(a);
if(!f){return null;}var e=f.get("friendlyName");var c=d.initDataRecord(a,e);g=d.newRecord(Ext.apply({accCode:f.get("code"),isNegative:f.get("isNegative"),accountCategoryId:f.get("accountCategoryId"),accountCategory:f.get("accountCategory")},c));
d.add([g]);}return g;},groupStore:function(){var f=this;f.sort("accCode","ASC");for(var d=0;d<this.getCount();
d++){var g=this.getAt(d);var a=g.get("accountCategoryId");var h=g.get("accountCategory");var b=f.queryBy(function(j,k){return j.get("accountCategoryId")==a;
});var c=b.getCount();var e=f.initDataRecord(a,h);f.insert(d+c,f.newRecord(Ext.apply({accountCategoryId:0,isNegative:h=="Revenue"},e)));
d+=c;}},populateStore:function(){var c=this;c._calculating=true;c.budDetailStore.each(function(d,f){var e=c.getByFscAccount(d.get("fscAccount"));
if(!!e){e.set("budget",c.decimal2(d.get("period"+c._periodTitle)));}});var a=new WebLight.util.MixedCollection();
c.appJDEGLTransactionStore.each(function(d){var e=d.get("fscAccount");if(a.indexOfKey(e)<0){a.add(e,[]);
}a.get(e).push(d.data);});a.eachKey(function(j,l){var k=c.getByFscAccount(j);if(!!k){k.set("noChildren",false);
k.set("subStore",l);var e=0,d=0,h=0,g=0;for(var f=0;f<l.length;f++){e+=l[f]["week1"];d+=l[f]["week2"];
h+=l[f]["week3"];g+=l[f]["week4"];}k.set("week1",c.decimal2(e));k.set("week2",c.decimal2(d));k.set("week3",c.decimal2(h));
k.set("week4",c.decimal2(g));}});var b=new WebLight.util.MixedCollection();c.previousAppJDEGLTransactionStore.each(function(d){var e=d.get("fscAccount");
if(b.indexOfKey(e)<0){b.add(e,[]);}b.get(e).push(d.data);});b.eachKey(function(d,g){var h=c.getByFscAccount(d);
if(!!h){var f=0;for(var e=0;e<g.length;e++){f+=(g[e]["week1"]+g[e]["week2"]+g[e]["week3"]+g[e]["week4"]);
}h.set("actual",c.decimal2(f));}});if(parseInt(c._periodTitle)==c.fscPeriodCount){c.projectionStore.each(function(d){var e=c.getByFscAccount(d.get("fscAccount"));
if(!!e){e.set("periodProjection1",d.get("period"+c.fscPeriodCount));}});c.nextProjectionStore.each(function(d){var e=c.getByFscAccount(d.get("fscAccount"));
if(!!e){e.set("periodProjection2",d.get("period1"));}});}else{c.projectionStore.each(function(d){var e=c.getByFscAccount(d.get("fscAccount"));
if(!!e){e.set("periodProjection1",d.get("period"+c._periodTitle));e.set("periodProjection2",d.get("period"+(parseInt(c._periodTitle)+1)));
}});}c.each(function(d){if(!d.get("week1")&&!d.get("week2")&&!d.get("week3")&&!d.get("week4")&&!d.get("budget")&&!d.get("periodProjection1")&&!d.get("periodProjection2")){c.remove(d);
}});c.groupStore();c._calculating=false;},decimal2:function(a){if(a&&typeof a=="number"){return Math.round(a*100)/100;
}return a;},calculateStore:function(){var c=this;if(c._calculating||c._addingTotalRow){return;}c._calculating=true;
var a=0,d=0;var b=c.queryBy(function(e){return !e.get("accCode");});b.each(function(f){var l=0,m=0,p=0,j=0,h=0,o=0,n=0,k=0;
var e=f.get("fscAccount");var g=c.queryBy(function(q){return q.get("accountCategoryId")==e;});g.each(function(q){var s=q.get("isNegative")&&!q.get("accCode");
if(e==0){s=!s;}l+=s?-q.get("week1"):q.get("week1");m+=s?-q.get("week2"):q.get("week2");p+=s?-q.get("week3"):q.get("week3");
j+=s?-q.get("week4"):q.get("week4");h+=s?-q.get("budget"):q.get("budget");o+=s?-q.get("actual"):q.get("actual");
n+=s?-q.get("periodProjection1"):q.get("periodProjection1");k+=s?-q.get("periodProjection2"):q.get("periodProjection2");
});f.set("week1",c.decimal2(l));f.set("week2",c.decimal2(m));f.set("week3",c.decimal2(p));f.set("week4",c.decimal2(j));
f.set("budget",c.decimal2(h));f.set("actual",c.decimal2(o));f.set("periodProjection1",c.decimal2(n));
f.set("periodProjection2",c.decimal2(k));});this.each(function(g){var f=g.get("week1")+g.get("week2")+g.get("week3")+g.get("week4");
g.set("total",c.decimal2(f));var h=g.get("isNegative")||g.get("fscAccount")==0;var e=(h||g.get("title")=="Revenue")?(f-g.get("budget")):(g.get("budget")-f);
g.set("variance",c.decimal2(e));});c._calculating=false;},getNextYear:function(){var c=this;var d=0;var a=c.fscYearStore.getById(c.fscYear).get("title");
var b=c.fscYearStore.queryBy(function(e){return parseInt(e.get("title"))==parseInt(a)+1;});if(!!b.get(0)){d=b.get(0).get("id");
}return d;},load:function(b,h,a,e,f){var d=this;if(d._loading){return;}d.clearStore();d.hcmHouseCode=b;
d.hcmJob=h;d.fscYear=a;d.fscPeriod=e;d._loadedStoreCount=0;d._periodTitle=f;d.budDetailStore.load(b,h,a);
d.appJDEGLTransactionStore.load(b,h,a,e,0);d.previousAppJDEGLTransactionStore.load(b,h,a,e,-1);d.projectionStore.load(b,h,a);
if(parseInt(d._periodTitle)==d.fscPeriodCount){var g=d.getNextYear();d.nextProjectionStore.load(b,h,g);
}var c=d.initDataRecord(0,"Total");d._totalRow=this.newRecord(c);},initDataRecord:function(a,c){var b={fscAccount:a,title:c,week1:0,week2:0,week3:0,week4:0,total:0,budget:0,variance:0,actual:0,periodProjection1:0,periodProjection2:0,noChildren:true};
return b;}});Bud.data.BudProjectedDetailStore=WebLight.extend(Bud.data.XmlStore,{url:"/net/crothall/chimes/fin/bud/act/Provider.aspx",moduleId:"bud",storeId:"budProjectedDetails",_hcmHouseCode:0,_fscYear:0,_hcmJob:0,constructor:function(a){Bud.data.BudProjectedDetailStore.superclass.constructor.call(this,a);
this.on({add:{fn:this.updateTotals},remove:{fn:this.updateTotals},update:{fn:this.updateTotals},datachanged:{fn:this.updateTotals}});
},updateTotals:function(){var a=this;this.suspendEvents(false);this.resumeEvents();this.fireEvent("datarefresh",this);
},getCriteria:function(){return{hcmHouseCode:this._hcmHouseCode,fscYear:this._fscYear,hcmJob:this._hcmJob};
},addAttributes:function(a){Ext.apply(a,{hcmHouseCode:this._hcmHouseCode,hcmJob:this._hcmJob,fscYear:this._fscYear});
},load:function(c,a,b){this._fscYear=b;this._hcmHouseCode=c;this._hcmJob=a;Bud.data.BudProjectedDetailStore.superclass.load.call(this);
},getChangedRecords:function(){var a=[];var b=this;var c=Bud.data.BudProjectedDetailStore.superclass.getChangedRecords.call(this);
Ext.each(c,function(d,e){if(!b.isEmptyRecord(d)){a.push(d);}});return a;},isEmptyRecord:function(a){var b;
var c=true;for(b=1;b<14;b++){c&=!a.get(String.format("period{0}",b));}return c;},fields:[{name:"id",mapping:"@id",type:"float"},{name:"hcmHouseCode",mapping:"@hcmHouseCode",type:"float"},{name:"hcmJob",mapping:"@hcmJob",type:"float"},{name:"fscYear",mapping:"@fscYear",type:"float"},{name:"fscPeriod",mapping:"@fscPeriod",type:"float"},{name:"fscAccount",mapping:"@fscAccount",type:"float"},{name:"modAt",mapping:"@modAt",type:"date"},{name:"modBy",mapping:"@modBy",type:"string"},{name:"period1",mapping:"@period1",type:"float"},{name:"period2",mapping:"@period2",type:"float"},{name:"period3",mapping:"@period3",type:"float"},{name:"period4",mapping:"@period4",type:"float"},{name:"period5",mapping:"@period5",type:"float"},{name:"period6",mapping:"@period6",type:"float"},{name:"period7",mapping:"@period7",type:"float"},{name:"period8",mapping:"@period8",type:"float"},{name:"period9",mapping:"@period9",type:"float"},{name:"period10",mapping:"@period10",type:"float"},{name:"period11",mapping:"@period11",type:"float"},{name:"period12",mapping:"@period12",type:"float"},{name:"period13",mapping:"@period13",type:"float"},{name:"period14",mapping:"@period14",type:"float"},{name:"total",type:"float"}]});
Bud.data.AppJDEGLTransactionDetailStore=WebLight.extend(Bud.data.XmlStore,{url:"/net/crothall/chimes/fin/glm/act/Provider.aspx",moduleId:"glm",storeId:"appJDEGLTransactionDetail2",_hcmHouseCode:0,_hcmJob:0,_fscYear:0,_fscPeriod:0,_fscAccount:0,getCriteria:function(){return{hcmHouseCode:this._hcmHouseCode,hcmJob:this._hcmJob,fscYear:this._fscYear,fscPeriod:this._fscPeriod,fscAccount:this._fscAccount};
},load:function(f,c,d,b,a){var e=this;this._hcmHouseCode=f;this._hcmJob=c;this._fscYear=d;this._fscPeriod=b;
this._fscAccount=a;Bud.data.AppJDEGLTransactionDetailStore.superclass.load.call(this);},fields:[{name:"id",mapping:"@id",type:"int"},{name:"hcmHouseCode",mapping:"@hcmHouseCode",type:"int"},{name:"hcmJob",mapping:"@hcmJob",type:"int"},{name:"fscYear",mapping:"@fscYear",type:"int"},{name:"fscPeriod",mapping:"@fscPeriod",type:"int"},{name:"fscAccount",mapping:"@fscAccount",type:"int"},{name:"amount",mapping:"@amount",type:"float"},{name:"crtdAt",mapping:"@crtdAt",type:"date"},{name:"crtdBy",mapping:"@crtdBy"},{name:"description",mapping:"@description"},{name:"documentNo",mapping:"@documentNo"},{name:"documentType",mapping:"@documentType"},{name:"glDate",mapping:"@glDate",type:"date"},{name:"invoiceDate",mapping:"@invoiceDate",type:"date"},{name:"invoiceNo",mapping:"@invoiceNo"},{name:"lineNumber",mapping:"@lineNumber"},{name:"post",mapping:"@post"},{name:"orderNumber",mapping:"@orderNumber"},{name:"tableType",mapping:"@tableType"},{name:"teamFinId",mapping:"@teamFinId"},{name:"vendor",mapping:"@vendor"},{name:"vendorNumber",mapping:"@vendorNumber"}]});
Bud.page.TransactionSummaryPage=WebLight.extend(WebLight.Page,{html:_builtInTemplate_a3bcf709[1],title:"Transaction Summary",_accountStore:null,_houseCodeStore:null,_jobCodeStore:null,_fiscalYearStore:null,_fscPeriodStore:null,_houseCodeComboBox:null,_hcmJobComboBox:null,_fscYearComboBox:null,_fscPeriodComboBox:null,_loadButton:null,_loadCount:0,_loadingData:false,_gridColumnModel:null,_gridGroupHeader:null,_transactionSummaryGrid:null,_transactionSummaryStore:null,_rowExpander:null,_currentHcmHouseCode:null,createBudgetFields:function(){var a=this;
this._houseCodeComboBox=new Ext.form.ComboBox({store:a._houseCodeStore,displayField:"name",valueField:"id",mode:"local",forceSelection:true,triggerAction:"all",selectOnFocus:true,layzeInit:false,typeAhead:true,allowBlank:false,minChars:1,width:290});
this._hcmJobComboBox=new Bud.form.DropdownList({store:a._jobCodeStore,displayField:"jobTitle",valueField:"jobId",allowBlank:true,width:150});
this._fscYearComboBox=new Bud.form.DropdownList({store:a._fiscalYearStore,displayField:"title",valueField:"id",allowBlank:true,width:90});
this._fscPeriodComboBox=new Bud.form.DropdownList({store:a._fscPeriodStore,displayField:"title",valueField:"id",allowBlank:true,width:90});
this._houseCodeComboBox.on("select",function(d,b,c){a._loaded=false;a._jobCodeStore.removeAll();a._currentHcmHouseCode=b.get("id");
a._hcmJobComboBox.setValue("");Bud.Context.setStickyHouseCode(b.get("appUnit"),b.get("id"),b.get("name"),b.get("brief"),b.get("hirNode"));
a._jobCodeStore.load(b.get("id"));});this._fscYearComboBox.on("select",function(d,b,c){Bud.Context.setStickyFiscalYear(b.get("id"),b.get("title"));
});this._fscPeriodComboBox.on("select",function(d,b,c){});this._houseCodeComboBox.on("blur",function(c){if(a._currentHcmHouseCode!=c.getValue()){a._currentHcmHouseCode=c.getValue();
var b=a._houseCodeStore.getById(a._currentHcmHouseCode);Bud.Context.setStickyHouseCode(b.get("appUnit"),b.get("id"),b.get("name"),b.get("brief"),b.get("hirNode"));
a._jobCodeStore.load(a._currentHcmHouseCode);}});this._fscYearComboBox.on("valuechange",function(b,c){a._fscPeriodStore.removeAll();
a._fscPeriodComboBox.setValue("");a._fscPeriodStore.load(b);});this._loadButton=new Ext.Button({text:" Load Data ",width:100,disabled:true,ctCls:"ux-button-1",handler:function(){a.loadGridStore();
}});this.addChildControl(this._houseCodeComboBox,"house-code-holder");this.addChildControl(this._hcmJobComboBox,"job-code-holder");
this.addChildControl(this._fscYearComboBox,"fiscal-year-holder");this.addChildControl(this._fscPeriodComboBox,"period-holder");
this.addChildControl(this._loadButton,"load-button-holder");},loadGridStore:function(){var c=this;c.getEl().mask("Loading...");
this._loadingData=true;var d=this._houseCodeComboBox.getValue();var f=this._hcmJobComboBox.getValue();
var e=this._fscYearComboBox.getValue();var a=this._fscPeriodComboBox.getValue();var g=this._fscPeriodComboBox.getRawValue();
this.refreshColumnModel();this.ensureGridCreated();var b=this.getWeeksTitle();$('div.x-grid3-hd-inner:contains("Weeks")').text(b);
this._transactionSummaryStore.on("load",function(h){c._transactionSummaryGrid.getView().refresh();c.getEl().unmask();
c._loadingData=false;});this._transactionSummaryStore.load(d,f,e,a,g);},getWeeksTitle:function(){var a=this._fscPeriodStore.getById(this._fscPeriodComboBox.getValue());
if(a){var c=Ext.util.Format.date(a.get("startDate"),"m/d");var b=Ext.util.Format.date(a.get("endDate"),"m/d");
return"Weeks:("+c+" - "+b+")";}},customRenderer:function(e,c,f,b,d,a){var g=[];switch(typeof e){case"string":if(!f.get("accCode")){g.push("text-align:right;");
}else{g.push("text-align:left;");}break;case"number":g.push("text-align:right;");break;}if(!f.get("accCode")){g.push("font-weight:bold;");
}if(d==9){if(e>0){g.push("color:#5B8E44;");}else{if(e<0){g.push("color:#FF0000;");}}}c.attr='style="'+g.join("")+'"';
if(Ext.isNumber(e)){return Ext.util.Format.number(e,"0,000.00");}return e;},refreshColumnModel:function(){var c=this;
this._rowExpander=new Ext.grid.RowExpander({tpl:'<div class="ux-row-expander-box"></div>',actAsTree:true,treeLeafProperty:"noChildren",listeners:{expand:function(l,j,f,h){var g=j.get("subStore");
var k=Ext.get(this.grid.getView().getRow(h)).child(".ux-row-expander-box");if(g&&g.length>0){c.createSubGrid(g,k);
}}}});var b=parseInt(this._fscPeriodComboBox.getRawValue());var d=this.getWeeksTitle();var a=false;if(c._fscPeriodStore.totalLength==12){a=true;
}this._gridGroupHeader=new Ext.ux.grid.ColumnHeaderGroup({rows:[[{header:"",colspan:3},{header:d,colspan:4,align:"center"},{header:"",colspan:3},{header:"Previous Period",align:"center"},{header:"Period Projections",colspan:2,align:"center"}]]});
var e=[this._rowExpander,{header:"Item(s)",dataIndex:"title",width:250},{header:"Code",dataIndex:"accCode",width:60},{header:"Week 1",dataIndex:"week1",hidden:a},{header:"Week 2",dataIndex:"week2",hidden:a},{header:"Week 3",dataIndex:"week3",hidden:a},{header:"Week 4",dataIndex:"week4",hidden:a},{header:"Total",dataIndex:"total"},{header:"Budget",dataIndex:"budget"},{header:"Variance",dataIndex:"variance"},{header:"Actual",dataIndex:"actual"}];
e.push({header:b,dataIndex:"periodProjection1"},{header:(b==c._fscPeriodStore.getCount())?1:(b+1),dataIndex:"periodProjection2"});
if(this._gridColumnModel){this._gridColumnModel.setConfig(e);}else{this._gridColumnModel=new Ext.grid.ColumnModel({defaults:{sortable:false,align:"center",renderer:c.customRenderer},columns:e});
}},ensureGridCreated:function(){if(!this._transactionSummaryGrid){this.createTransactionSummaryGrid();
}},_detailGrid:null,_detailStore:null,_detailWin:null,createDetailGrid:function(){var a=this;this._detailGrid=new Bud.grid.GridPanel({border:false,header:false,height:400,enableHdMenu:false,stripeRows:true,height:380,loadMask:true,cm:new Ext.grid.ColumnModel({defaults:{sortable:false,width:60,align:"center"},columns:[{header:"GL Ticket<br />Date",dataIndex:"glDate",renderer:Ext.util.Format.dateRenderer("m/d/y")},{header:"Document<br />Number",dataIndex:"documentNo"},{header:"Invoice<br />Number",dataIndex:"invoiceNo"},{header:"Invoice<br />Date",dataIndex:"invoiceDate",renderer:Ext.util.Format.dateRenderer("m/d/y")},{header:"PO<br />Number",dataIndex:"orderNumber"},{header:"&nbsp;<br />Vendor",dataIndex:"vendor",width:100},{header:"&nbsp;<br />Description",dataIndex:"description",width:100},{header:"&nbsp;<br />Amount",dataIndex:"amount"},{header:"Document<br />Type",dataIndex:"documentType"},{header:"Import<br />Date",dataIndex:"crtdAt",renderer:Ext.util.Format.dateRenderer("m/d/y")}]}),store:this._detailStore});
},PopupSubGridRowDetail:function(b){var a=this;this.__record=b;var c=function(){var h=a.__record.get("hcmHouseCode");
var f=a.__record.get("hcmJob");var g=a.__record.get("fscYear");var e=a.__record.get("fscPeriod");var d=a.__record.get("fscAccount");
a._detailStore.removeAll();a._detailStore.load(h,f,g,e,d);};if(!this._detailWin){this.createDetailGrid();
this._detailWin=new Ext.Window({modal:true,width:750,closeAction:"hide",items:[this._detailGrid]});this._detailWin.on("show",function(){c();
});}this._detailWin.show();},createSubGrid:function(d,b){var j=this;var e=[];var k=function(n){var o=null;
Ext.each(e,function(p){if(p.vendor==n.vendor){o=p;return false;}});if(null==o){o=Ext.applyIf({week1:0,week2:0,week3:0,week4:0,total:0},n);
e.push(o);}return o;};var m=function(n,o){n.id=o.id;n.week1+=o.week1||0;n.week2+=o.week2||0;n.week3+=o.week3||0;
n.week4+=o.week4||0;n.total+=n.week1+n.week2+n.week3+n.week4;};Ext.each(d,function(o,p){var n=k(o);m(n,o);
});var a=new Bud.data.AppJDEGLTransactionStore();Ext.each(e,function(n,o){a.add(a.newRecord(n));});a.sort([{field:"vendor",direction:"ASC"},{field:"week1",direction:"ASC"},{field:"week2",direction:"ASC"},{field:"week3",direction:"ASC"},{field:"week4",direction:"ASC"}]);
var f=new Ext.grid.RowExpander({alwaysAsLeaf:true,actAsTree:true});var g=[f,{dataIndex:"vendor",width:285},{dataIndex:"week1"},{dataIndex:"week2"},{dataIndex:"week3"},{dataIndex:"week4"}];
var h=this._fscYearComboBox.getValue();if(h>=4){g=[f,{dataIndex:"vendor",width:285},{dataIndex:"total"}];
}var c=new Ext.grid.ColumnModel({defaults:{sortable:false,align:"right",renderer:function(n){if(Ext.isNumber(n)){return Ext.util.Format.number(n,"0,000.00");
}return n;}},columns:g});var l=new WebLight.grid.GridPanel({style:"margin:5px 0",autoHeight:true,plugins:f,disableSelection:true,stripeRows:true,enableHdMenu:false,border:false,header:false,cm:c,store:a});
l.on("rowdblclick",function(n,p,o){j.PopupSubGridRowDetail(n.getStore().getAt(p));});b&&l.render(b);return l;
},createTransactionSummaryGrid:function(){var a=this;this.refreshColumnModel();this._transactionSummaryGrid=new WebLight.grid.GridPanel({enableHdMenu:false,height:400,ctCls:"ux-grid-1",cm:this._gridColumnModel,plugins:[this._gridGroupHeader,this._rowExpander],store:this._transactionSummaryStore});
this.addChildControl(this._transactionSummaryGrid,"transaction-summary-grid");},createChildControls:function(){var a=this;
this._houseCodeStore=new Bud.data.HouseCodeStore();this._jobCodeStore=new Bud.data.JobCodeStore();this._fiscalYearStore=new Bud.data.FiscalYearStore();
this._fscPeriodStore=new Bud.data.FiscalPeriodStore();this._accountStore=new Bud.data.BudgetAccountStore();
this._detailStore=new Bud.data.AppJDEGLTransactionDetailStore();this._transactionSummaryStore=new Bud.data.TransactionSummaryStore({fscAccountStore:this._accountStore,fscYearStore:this._fiscalYearStore,fscPeriodStore:this._fscPeriodStore});
this.createBudgetFields();Bud.page.TransactionSummaryPage.superclass.createChildControls.call(this);},dataBind:function(){var a=this;
this.getEl().mask("Loading...");this._jobCodeStore.on("load",function(b,c,d){if(c.length>0){a._hcmJobComboBox.setValue(c[0].get("jobId"));
}else{a._hcmJobComboBox.setValue("");}a._loadCount++;a.enableLoadButton();});this._houseCodeStore.on("load",function(b,c,d){if(c.length>0){var e;
if(Bud.Context.getStickyHcmHouseCode()!=0){a._houseCodeComboBox.setValue(Bud.Context.getStickyHcmHouseCode());
e=Bud.Context.getStickyHcmHouseCode();}else{a._houseCodeComboBox.setValue(c[0].get("id"));e=c[0].get("id");
}a._jobCodeStore.load(e);}else{a._houseCodeComboBox.setValue("");}a._loadCount++;});a._fscPeriodStore.on("load",function(b,c,d){if(c.length>0){var e=a._fscPeriodStore.queryBy(function(f){var g=new Date();
return f.get("startDate")<=g&&f.get("endDate")>=g;});if(e.getCount()>0){a._fscPeriodComboBox.setValue(e.get(0).get("id"));
}else{a._fscPeriodComboBox.setValue(c[0].get("id"));}}else{a._fscPeriodComboBox.setValue("");}a._transactionSummaryStore.fscPeriodCount=c.length;
console.log(c.length);a._loadCount++;a.enableLoadButton();});this._fiscalYearStore.on("load",function(b,c,d){if(c.length>0){if(parent&&parent.fin&&parent.fin.appUI&&parent.fin.appUI.glbFscYear!=0){a._fscYearComboBox.setValue(parent.fin.appUI.glbFscYear);
a._fscPeriodStore.load(parent.fin.appUI.glbFscYear);}else{a._fscYearComboBox.setValue(c[0].get("id"));
a._fscPeriodStore.load(c[0].get("id"));}}else{a._fscYearComboBox.setValue("");}a._loadCount++;});this._accountStore.on("load",function(){a._loadCount++;
a.enableLoadButton();});this._accountStore.load();this._houseCodeStore.load();this._fiscalYearStore.load();
Bud.page.TransactionSummaryPage.superclass.dataBind.call(this);},enableLoadButton:function(){var a=this;
if(this._loadCount==6){this.getEl().unmask();this._loadButton.enable();this.ensureGridCreated();}}});
WebLight.PageMgr.registerType("transactionsummary",Bud.page.TransactionSummaryPage);